[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Któremu nieasynchronicznemu traitowi z biblioteki standardowej Rusta najbardziej odpowiada trait `Stream`?
"""
prompt.distractors = ["`Write`", "`Index`", "`Sync`"]
answer.answer = "`Iterator`"
context = """
Trait `Stream` zapewnia asynchroniczną wersję iteratora w Ruście.
"""
id = "f94a87f0-a4d6-4cd6-bcee-dfcc606f8ec2"

[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Załóżmy, że masz strumień, który zwraca sekwencję `["A", "B", "C"]`, i drugi strumień, który zwraca sekwencję ["D", "E", "F"].
Nie wiesz, kiedy każdy ze strumieni wyemituje poszczególne znaki, wiesz tylko, że pojawią się w podanych sekwencjach.
Wyobraź sobie, że łączysz te strumienie i wypisujesz każdy znak. Zaznacz każdy z poniższych łańcuchów wyjściowych, który mógłby zostać wypisany.
"""
prompt.distractors = [
  "ACBDEF",
  "CFBEAD"
]
answer.answer = [
  "ABDEFC",
  "DEFABC"
]
context = """
Łączenie zawsze zachowuje kolejność w obrębie każdego strumienia, więc na przykład "B" nie może wystąpić przed "C".
"""
id = "84452eff-13df-4fcb-91ea-1f504d5bfaf0"
