[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Rozważ następującą funkcję:

```rust
async fn print_letters() {
  let a = async { print!("A"); };
  let b = async { print!("B"); };
  let c = async { print!("C"); };
  c.await;
  b.await;
  a.await;
}
```

Które z poniższych łańcuchów mogą zostać wypisane po wykonaniu `print_letters().await`?
"""
prompt.distractors = ["`ABC`", "`BCA`", "`ACB`"]
answer.answer = ["`CBA`"]
context = """
Ten program zachowuje się deterministycznie. Wypisywanie nie następuje, dopóki nie zaczniemy oczekiwać na bloki async.
Na bloki oczekujemy w kolejności `c`/`b`/`a`, więc program wypisze wyłącznie `CBA`.
"""
id = "8f62c158-525a-43a2-aa6a-0cc106cada10"

[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Załóżmy, że masz do dyspozycji funkcję pomocniczą `wait_all(a, b)` o następującym zachowaniu:
* `wait_all` gwarantuje, że `a` i `b` zostaną wykonane do końca.
* `wait_all` nie daje żadnych gwarancji dotyczących sprawiedliwości ani początkowej kolejności wykonania.

Mając dany następujący kod:

```rust
async fn print_letters() {
  let fut1 = async { 
    print!("A");
    sleep().await;
    print!("B");
  };
  let fut2 = async {
    print!("C");
    sleep().await;
    print!("D");
  }
  wait_all(fut1, fut2).await;
}
```

Które z poniższych łańcuchów mogą zostać wypisane po wykonaniu `print_letters().await`?
"""
prompt.distractors = ["`DABC`"]
answer.answer = [
  "`ABCD`", "`CADB`", "`ACBD`"
]
context = """
Hipotetyczny prymityw `wait_all` działa jak `join`, ale daje mniej gwarancji. Przy samej specyfikacji z tego zadania dowolny przeplot
obu future’ów jest poprawne. Jedynym niepoprawnym wynikiem jest taki, który odwraca kolejność wykonania programu, czyli `DABC`, w którym `D` zostałoby wypisane przed `C`.
"""
id = "4b28f13e-9781-4d29-b886-7639fa527f36"

[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Załóżmy, że masz do dyspozycji kanał do przekazywania komunikatów `channel()`, który jest nieblokujący i *ograniczony*, 
co oznacza, że `send` zwraca future, który kończy się, gdy w kanale zwolni się miejsce.
Załóżmy też, że masz funkcję `join(a, b)`, która *sprawiedliwie* czeka na zakończenie obu swoich argumentów. Mając dany następujący kod asynchroniczny:

```rust
let (tx, mut rx) = channel(16);
let recv_fut = rx.recv();
let send_fut = tx.send(0);
let (n, _) = join(recv_fut, send_fut).await;
println!("{}", n.unwrap());
```

Co się stanie w wyniku wykonania tego kodu?
"""
prompt.distractors = [
  "Program wypisuje `0` i zapętla się w nieskończoność",
  "Program nic nie wypisuje i zapętla się w nieskończoność",
  "Program panikuje"
]
answer.answer = "Program wypisuje `0` i kończy działanie"
context = """
Ponieważ kanał jest nieblokujący, możemy utworzyć future odbierający przed wysłaniem, nie zapętlając się w nieskończoność.
"""
id = "e23b7c48-3780-44e7-8ea4-df35032548a1"
