[[questions]]
type = "MultipleChoice"
prompt.prompt = "Który z poniższych opisów najlepiej oddaje działanie `f.await` dla danego future’a `f`?"
prompt.distractors = [
  "Jednokrotnie wywołuje `f.poll()`, które blokuje w miejscu, dopóki `f` nie będzie gotowy",
  "Wywołuje `f.poll()` w pętli, kończąc ją, jeśli `f` jest gotowy, lub natychmiast odpytując ponownie, jeśli `f` nie jest gotowy",
  "Jednokrotnie wywołuje `f.push(...)`, które wykonuje wywołanie zwrotne zawierające pozostały kod po `f.await`, gdy tylko `f` będzie gotowy"
]
answer.answer = "Wywołuje `f.poll()` w pętli, kończąc ją, jeśli `f` jest gotowy, lub oddając sterowanie asynchronicznemu środowisku uruchomieniowemu, jeśli `f` nie jest gotowy"
context = """
Rust wykonuje future’y w modelu opartym na odpytywaniu. Punkt oczekiwania jest rozwijany do pętli, która wielokrotnie wywołuje `.poll()`
i po każdym nieudanym odpytaniu oddaje sterowanie asynchronicznemu środowisku uruchomieniowemu, aby mógł się wykonać inny kod asynchroniczny.
Środowisko uruchomieniowe może później „obudzić” kod `f.await`, aby ponownie odpytać `f`.
"""
id = "c4d90f3c-7286-4272-921c-241b266e9f91"

[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Wyobraź sobie, że Rust nie wymaga przypinania future’ów, aby można je było odpytywać.
Która z poniższych funkcji asynchronicznych mogłaby potencjalnie spowodować niezdefiniowane zachowanie, gdyby nie była przypięta?
"""
prompt.distractors = [
"""
```rust
async fn example(x: &i32) -> i32 {
    sleep(Duration::from_secs(1)).await;
    *y
}
```
""",
"""
```rust
async fn example(x: Vec<i32>) -> i32 {
    sleep(Duration::from_secs(1)).await;
    x[0]
}
```
""",
"""
```rust
async fn example() -> i32 {
    let x = 0;
    sleep(Duration::from_secs(1)).await;
    x
}
```
""",
]
answer.answer = """
```rust
async fn example(x: i32) -> i32 {
    let y = &x;
    sleep(Duration::from_secs(1)).await;
    *y
}
```
"""
context = """
Główny problem, który rozwiązuje przypinanie, to samoreferencja, czyli future zawierający wskaźnik do samego siebie.
Dzieje się tak, gdy blok async zawiera zmienną lokalną, która odwołuje się do innej zmiennej lokalnej w tym future’ze.
W tym przykładzie byłoby to `y = &x`.
"""
id = "bc8b4acb-d111-4fec-b89a-e5d1bc77c8f2"
