[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Mając funkcję `sleep(d)`, która usypia na podany czas, rozważ następujący kod:

```rust
let futs: Vec<_> = [1, 2, 3].iter().map(|n| async move {
  sleep(Duration::from_secs(5)).await;
  n + 1
}).collect();

for fut in futs {
  let n = fut.await;
  println!("{n}");
}
```

Ile mniej więcej sekund powinno zająć wykonanie tej funkcji?
"""
prompt.distractors = ["5", "0"]
answer.answer = "15"
context = """
Bez użycia funkcji takiej jak `join_all` future’y nie będą wykonywać się współbieżnie. Dlatego ten kod będzie się wykonywał 15 sekund (po 5 sekund na każdy element listy).
"""
id = "68680e2e-7a9f-4cee-8080-70e57fe5a2b3"

[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Załóżmy, że projektujesz funkcję pomocniczą o następującej specyfikacji:

> `map_stringify` przyjmuje dwa argumenty: wektor danych wejściowych oraz funkcję asynchroniczną, która przekształca dane wejściowe w wynik,
> przy czym wyniki można przekształcić w łańcuchy znaków.
> `map_stringify` zwraca wektor wyników przekształconych w łańcuchy znaków.

Która sygnatura typu funkcji najlepiej oddaje tę specyfikację?
"""
prompt.distractors = [
"""
```rust
async fn map_stringify(
  inputs: Vec<String>, f: impl Future<Output = String>
) -> Vec<String>
```
""",
"""
```rust
fn map_stringify<I, O, F>(
  inputs: Vec<I>, f: impl Fn(I) -> O,
) -> Vec<impl Future<Output = String>>
where
  O: ToString,  
```
""",
"""
```rust
async fn map_stringify<I, F>(
  inputs: Vec<I>, f: impl Fn(I) -> F, 
) -> Vec<String>
where
  F: Future + ToString,
```
"""]
answer.answer = """
```rust
async fn map_stringify<I, O, F>(
  inputs: Vec<I>, f: impl Fn(I) -> F, 
) -> Vec<String>
where
  O: ToString,
  F: Future<Output = O>,
```
"""
context = """
Oto jedna z możliwych implementacji tej funkcji:

```rust
async fn map_stringify<I, O, F>(
  f: impl Fn(I) -> F, inputs: Vec<I>
) -> Vec<String>
where
  O: ToString,
  F: Future<Output = O>,
{
  let f = &f;
  let futs = inputs
    .into_iter()
    .map(|input| async move { f(input).await.to_string() });
  futures::future::join_all(futs).await
}
```
"""
id = "b42a9c5b-bfe7-4d6f-967a-f8ff2a6faa0d"

[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Załóżmy, że piszesz program, który musi wykonać pewien kod asynchroniczny, ale co 500 ms sprawdzać, czy obliczenia należy przerwać.
Która funkcja pomocnicza najlepiej nadaje się do realizacji tego zadania?
"""
prompt.distractors = [
  "`join`",
  "`yield`",
  "`spawn` / `spawn_task`"
]
answer.answer = "`race` / `select`"
context = """
Możesz na przykład wykonywać w pętli `select` z długotrwałym future’em i future’em usypiającym, który kończy się po 500 ms.
"""
id = "7da21e95-8e03-412b-8c4d-90ccfc8c6802"
