[[questions]]
type = "MultipleChoice"
prompt.prompt = "Co należy zrobić, jeśli chcesz poczekać na future’a w kodzie nieasynchronicznym?"
prompt.distractors = [
  "Umieścić `.await` bezpośrednio po future’ze",
  "Przekazać future’a do wbudowanego w Rusta asynchronicznego środowiska uruchomieniowego",
  "Opakować future’a w blok `async` i użyć `.await` na tym bloku",  
]
answer.answer = "Przekazać future’a do zewnętrznego asynchronicznego środowiska uruchomieniowego" 
context = """
Rust nie pozwala używać `.await` poza blokami lub funkcjami `async`. Rust nie ma też wbudowanego asynchronicznego środowiska uruchomieniowego.
Należy użyć zewnętrznego asynchronicznego środowiska uruchomieniowego, takiego jak `tokio` lub `trpl`. 
"""
id = "de2a5023-dd5c-412e-8425-c8ed638f18f0"

[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Do jakiej sygnatury typu rozwija się poniższa funkcja asynchroniczna?

```rust
async fn calculate(nums: &[i32]) -> i32 {
  /* ... */
}
```
"""
prompt.distractors = [
  """
```rust
fn calculate<'a>(nums: &'a [i32], output: &mut impl Future<Output = i32> + 'a);
```
  """,
  """
```rust
fn calculate(nums: &'_ [i32]) -> i32 as Future;
```
  """,
  """
```rust
fn calculate() -> impl for<'a> Future<Input = &'a [i32], Output = i32> + 'a;
```
  """
]
answer.answer = """
```rust
fn calculate<'a>(nums: &'a [i32]) -> impl Future<Output = i32> + 'a;
```
"""
context = """
Funkcja asynchroniczna zwraca anonimowy typ implementujący trait `Future`, którego wynikiem jest typ zwracany funkcji. 
Tutaj zapisujemy to więc jako `impl Future<Output = i32>`. Future przechwytuje wszystkie czasy życia z argumentów funkcji.
Dlatego zwracany typ ma ograniczenie `+ 'a`, a wejściowy wycinek ma typ `&'a [i32]`. Oznacza to, że wycinek 
musi żyć co najmniej tak długo jak future, który go przechwytuje.
"""
id = "9c000322-464b-4d34-9e30-55591f9283d2"
