[[questions]]
id = "6286342a-84c1-47c5-bfd2-f34b51df813c"
type = "ShortAnswer"
prompt.prompt = "Jak nazywa się narzędzie wiersza poleceń do zarządzania wersją Rusta na twoim komputerze?"
answer.answer = "rustup"
context = """
Na przykład możesz wpisać `rustup update`, aby pobrać najnowszą wersję Rusta.
"""
