[[questions]]
id = "87c3b09e-84d3-49d7-8680-0b2d068a7fc5"
type = "ShortAnswer"
prompt.prompt = "Każdy wykonywalny program w Ruście musi zawierać funkcję o nazwie:"
answer.answer = "main"
context = """
W programie dodajesz funkcję main w ten sposób:

```
fn main() {
  // your code here
}
```
"""

[[questions]]
id = "0d78d302-eb3d-4ac7-a1ac-f2d661810744"
type = "MultipleChoice"
prompt.prompt = """
Załóżmy, że masz następujący program w pliku `hello.rs`:

```
fn main() {
  println!("Hello world!");
}
```

Następnie uruchamiasz w wierszu poleceń polecenie `rustc hello.rs`. Które stwierdzenie najlepiej opisuje, co się wtedy stanie?
"""
answer.answer = "`rustc` generuje wykonywalny plik binarny o nazwie `hello`"
prompt.distractors = [
  "`rustc` wypisze błąd, ponieważ ten program jest niepoprawny",
  "`rustc` wykonuje program i wypisuje `Hello world!`",
  "`rustc` formatuje `hello.rs` zgodnie z przewodnikiem po stylu Rusta"
]
context = """
Polecenie `rustc` sprawdza i kompiluje program, ale go nie wykonuje.
"""
