[[questions]]
id = "c1b7cc2e-b5fb-4b67-b0bb-600d82931f08"
type = "MultipleChoice"
prompt.prompt = """
Załóżmy, że masz świeżo pobrany projekt Cargo i uruchamiasz `cargo run` w wierszu poleceń. Które stwierdzenie NIE jest prawdziwe w odniesieniu do tego, co stanie się dalej?
"""
answer.answer = "Cargo obserwuje zmiany w plikach i po każdej zmianie ponownie uruchamia plik binarny"
prompt.distractors = [
  "Cargo pobiera i buduje wszystkie zależności projektu",
  "Cargo buduje projekt do pliku binarnego w katalogu `target/debug`",
  "Cargo uruchamia plik binarny projektu"
]
context = """
Cargo domyślnie nie obserwuje twoich plików. W tym celu możesz jednak użyć wtyczek takich jak [cargo-watch](https://crates.io/crates/cargo-watch).
"""
