[[questions]]
id = "30212501-00d5-4ef6-838f-3df5112ee7ed"
type = "Tracing"
prompt.program = """
fn main() {
  let message = "The temperature today is:";
  let x = [message, 100];
  println!("{} {}", x[0], x[1]);
}
"""
answer.doesCompile = false
answer.lineNumber = 3
context = """
Tablica może zawierać elementy tylko jednego typu. Składnia `[message, 100]` tworzy tablicę z dwoma elementami.
Zmienna `message` jest łańcuchem znaków, a stała `100` jest liczbą.
"""

[[questions]]
id = "4e632a23-24cc-4c29-8935-cf6b62c3764b"
type = "Tracing"
prompt.program = """
fn main() {
  let t = ([1; 2], [3; 4]);
  let (a, b) = t;
  println!("{}", a[0] + t.1[0]); 
}
"""
answer.doesCompile = true
answer.stdout = "4"
context = """
Składnia `[x; y]` deklaruje tablicę z `y` kopiami wartości `x`. Składnia `(a, b)` destrukturyzuje `t` i wiąże `a` z `[1; 2]`. 
Składnia `t.1` odwołuje się do drugiego elementu `t`, czyli `[3; 4]`.
"""