[[questions]]
id = "a48e524e-852c-400c-ae68-5c76a6761596"
type = "MultipleChoice"
prompt.prompt = "Które z poniższych zdań poprawnie opisuje różnicę między deklarowaniem zmiennej za pomocą `let` a za pomocą `const`?"
answer.answer = "`const` można używać w zasięgu globalnym, a `let` tylko wewnątrz funkcji"
prompt.distractors = [
  "To po prostu różne składnie deklarowania zmiennych o tej samej semantyce",
  "Kompilator zgłosi błąd, jeśli nazwa zmiennej `const` nie jest zapisana w stylu `UPPER_SNAKE_CASE`",
  "Stałej `const` można przypisać tylko literał, a nie wyrażenie wymagające obliczeń"
]

[[questions]]
id = "d209784f-cc52-4451-8049-ad204e89d587"
type = "Tracing"
prompt.program = """
const TWO: u32 = 1 + 1;
fn main() {
  println!("{TWO}");
}
"""
answer.doesCompile = true
answer.stdout = "2"
context = """
Zmienne `const` można definiować poza funkcją, a do ich inicjalizacji można używać ograniczonych form obliczeń.
"""