[[questions]]
id = "e582f00a-2f28-46e4-ae1b-77fd223cca4f"
type = "MultipleChoice"
prompt.prompt = "Największa liczba, jaką można zapisać w typie `i128`, to:"
answer.answer = "2<sup>127</sup> - 1"
prompt.distractors = [
  "2<sup>128</sup>",
  "2<sup>128</sup> - 1",
  "2<sup>127</sup>",
]
prompt.answerIndex = 3
context = """
Ogólnie liczba ze znakiem o *n* bitach może reprezentować liczby od -(2<sup>n - 1</sup>) do 2<sup>n - 1</sup> - 1.
"""

[[questions]]
id = "3a92246b-a43c-4658-980b-335d7632ddcb"
type = "MultipleChoice"
prompt.prompt = "Jeśli `x : u8 = 0`, co się stanie przy obliczaniu `x - 1`?"
answer.answer = "To zależy od trybu kompilacji." 
prompt.distractors = [
  "Program zawsze spanikuje.",
  "Wynikiem zawsze będzie 255.",
]
context = """
To wyrażenie spowoduje panikę w trybie debugowania, a w trybie wydania zwróci 255.
"""

[[questions]]
id = "9bcac1a1-d2df-4a51-b399-7fd8a6042cc2"
type = "Tracing"
prompt.program = """
fn main() {
  let x: fsize = 2.0;
  println!("{x}");
}
"""
answer.doesCompile = false
answer.lineNumber = 2
context = """
Typ `fsize` nie istnieje. Liczby zmiennoprzecinkowe muszą być typu `f32` albo `f64`.
"""