[[questions]]
id = "8bd8d8bc-e61e-48c7-ba78-0c89339e5995"
type = "MultipleChoice"
prompt.prompt = "Które zdanie najlepiej opisuje, co oznacza, że zmienna `x` jest niemutowalna?"
answer.answer = "Po przypisaniu wartości `x` nie można zmienić."
prompt.distractors = [
  "`x` jest przechowywana w niemutowalnym obszarze pamięci.",
  "Po zdefiniowaniu `x` można zmienić najwyżej raz.",
  "Nie można utworzyć referencji do `x`."
]
context = """
Niemutowalny oznacza „nie mutowalny”, czyli niezmienialny.
"""

[[questions]]
id = "dcf53c67-b3c9-4c54-8da0-90749cc669e8"
type = "ShortAnswer"
prompt.prompt = "Jakie słowo kluczowe umieszcza się po `let`, aby zaznaczyć, że zmienną można modyfikować?"
answer.answer = "mut"
context = """
Na przykład mutowalną zmienną `x` możesz utworzyć, pisząc: `let mut x = 1`.
"""

[[questions]]
id = "77f9f143-45a6-4f08-bd87-72bc50c00693"
type = "Tracing"
prompt.program = """
fn main() {
  let x = 1;
  println!("{x}");
  x += 1;
  println!("{x}");
}
"""
answer.doesCompile = false
answer.lineNumber = 4
context = """
To błąd kompilacji, ponieważ linia 4 próbuje zmodyfikować `x`, choć `x` nie jest oznaczona jako `mut`.
"""