[[questions]]
id = "5080616f-6f4c-43f7-aa3a-8b23f2798937"
type = "Tracing"
prompt.program = """
fn incr(n: &mut i32) {
  *n += 1;
}

fn main() {
  let mut n = 1;
  incr(&n);
  println!("{n}");
}
"""
answer.doesCompile = false
answer.lineNumber = 7
context = """
Choć `n` jest oznaczone jako `mut`, referencja do `n` również musi być oznaczona jako `mut`.
Poprawna wersja tego programu zawierałaby więc `incr(&mut n)`.
"""


[[questions]]
id = "e9846c5d-1254-4420-9986-dae4af86b9af"
type = "Tracing"
prompt.program = """
fn main() {
  let mut s = String::from("hello");
  let s2 = &s;
  let s3 = &mut s;
  s3.push_str(" world");
  println!("{s2}");
}
"""
answer.doesCompile = false
answer.lineNumber = 6
context = """
Nie wolno używać mutowalnej referencji do wartości (`s3`), dopóki żywa jest niemutowalna referencja
(`s2`).
"""

[[questions]]
id = "80f6bcd6-b74a-4da3-a014-d423c82ce405"
type = "MultipleChoice"
prompt.prompt = """
Rozważ tę funkcję w Ruście, która dodaje liczbę na koniec wektora, a następnie usuwa i zwraca liczbę z początku wektora:

```
fn give_and_take(v: &Vec<i32>, n: i32) -> i32 {
    v.push(n);
    v.remove(0)
}
```

Zwykle przy próbie skompilowania tej funkcji kompilator zgłasza następujący błąd:

```text
error[E0596]: cannot borrow `*v` as mutable, as it is behind a `&` reference
 --> test.rs:2:5
  |
1 | fn give_and_take(v: &Vec<i32>, n: i32) -> i32 {
  |                     --------- help: consider changing this to be a mutable reference: `&mut Vec<i32>`
2 |     v.push(n);
  |     ^^^^^^^^^ `v` is a `&` reference, so the data it refers to cannot be borrowed as mutable
```

Załóż, że kompilator NIE odrzucił tej funkcji. Zaznacz każdy z poniższych programów (jeśli taki jest), który po uruchomieniu
mógłby spowodować niezdefiniowane zachowanie. Jeśli żaden z tych programów nie mógłby spowodować niezdefiniowanego zachowania,
zaznacz „Żaden z tych programów”.
"""
answer.answer = [
"""
```
let v = vec![1, 2, 3];
let n = &v[0];
give_and_take(&v, 4);
println!("{}", n);
```
""",
]
prompt.distractors = [
"""
```
let v = vec![1, 2, 3];
let v2 = &v;
give_and_take(&v, 4);
println!("{}", v2[0]);
```
""",
"""
```
let v = vec![1, 2, 3];
let n = &v[0];
let k = give_and_take(&v, 4);
println!("{}", k);
```
""",
"Żaden z tych programów"
]
context = """
Jak widzieliśmy wcześniej w tym podrozdziale, `v.push(n)` może sprawić, że `v` realokuje swoją zawartość, co unieważnia wszystkie referencje do elementów `v` na stercie.
Dlatego wywołanie `give_and_take(&v, 4)` sprawi, że wcześniej utworzone referencje do elementów będą wskazywać na nieprawidłową pamięć. Dwa programy, które wiążą `let n = &v[0]`
przed `give_and_take`, są kandydatami do niezdefiniowanego zachowania. `let v2 = &v` nie jest kandydatem, ponieważ modyfikacja `v` w rzeczywistości nie unieważnia
referencji do samego kontenera `v`.

Program, który wykonuje `println!("{}", n)`, spowoduje niezdefiniowane zachowanie, odczytując nieprawidłową pamięć. Program, który wykonuje `println!("{}", k)`, nie spowoduje
niezdefiniowanego zachowania, ponieważ nie używa unieważnionej referencji.
"""