[[questions]]
id = "889ca9ac-0f4b-4abf-82c4-be9cd4d4f7ad"
type = "MultipleChoice"
prompt.prompt = "Które z poniższych NIE jest rodzajem niezdefiniowanego zachowania?"
answer.answer = "Przechowywanie w ramce stosu wskaźnika na zwolnioną pamięć"
prompt.distractors = [
  "Użycie wskaźnika, który wskazuje na zwolnioną pamięć",
  "Ponowne zwolnienie tej samej pamięci",
  "Użycie wartości niebędącej wartością logiczną jako warunku `if`"
]
context = """
Przechowywanie wskaźnika na zwolnioną pamięć w ramce stosu może być całkowicie bezpieczne. 
Ważne jest, by nie *używać* już tego wskaźnika, np. nie odczytywać go ani nie zwalniać.
"""

[[questions]]
id = "94425a4e-043e-47f8-9fba-c5b09fb60aa3"
type = "Tracing"
prompt.program = """
fn add_suffix(mut s: String) -> String {
  s.push_str(" world");
  s
}

fn main() {
  let s = String::from("hello");
  let s2 = add_suffix(s);
  println!("{}", s2);
}
"""
answer.doesCompile = true
answer.stdout = "hello world"
context = """
Ten program jest poprawny, ponieważ `s` nie jest używane po przeniesieniu do `add_suffix`.
"""

[[questions]]
id = "c00e3638-861b-4f9e-a55c-bfb67af79280"
type = "Tracing"
prompt.program = """
fn main() {
  let s = String::from("hello");
  let s2;
  let b = false;
  if b {
    s2 = s;
  }
  println!("{}", s);
}
"""
answer.doesCompile = false
answer.lineNumber = 8
context = """
Ponieważ `s` może zostać przeniesione wewnątrz instrukcji if, użycie go w wierszu 8 jest niedozwolone.
Choć w tym programie instrukcja if nigdy się nie wykona, bo `b` zawsze ma wartość `false`,
Rust w ogólności nie próbuje ustalać, czy instrukcje if się wykonają, czy nie. Rust po prostu
zakłada, że instrukcja *może* się wykonać, a więc `s` *może* zostać przeniesione.
"""

[[questions]]
id = "f7d67c11-60bb-4d92-8cc2-8ce82cf4c974"
type = "MultipleChoice"
prompt.prompt = """
Załóżmy, że mamy funkcję, która przenosi box, na przykład taką:
```
fn move_a_box(b: Box<i32>) {
  // This space intentionally left blank
}
```

Poniżej znajdują się cztery fragmenty kodu, które kompilator Rusta odrzuca. 
Wyobraź sobie, że Rust pozwala je skompilować i uruchomić. 
Zaznacz każdy fragment, który spowodowałby niezdefiniowane zachowanie, albo zaznacz 
„Żaden z tych fragmentów”, jeśli żaden z nich nie spowodowałby niezdefiniowanego zachowania.
"""
answer.answer = [
"""
```
let b = Box::new(0);
let b2 = b;
move_a_box(b);
```
""",
"""
```
let b = Box::new(0);
move_a_box(b);
println!("{}", b);
```
""",
"""
```
let b = Box::new(0);
move_a_box(b);
let b2 = b;
```
"""
]
prompt.distractors = [
"""
```
let b = Box::new(0);
let b2 = b;
println!("{}", b);
move_a_box(b2);
```
""",
"Żaden z tych fragmentów"
]
context = """
Kluczowe jest to, że gdy box zostaje przekazany do `move_a_box`, jego pamięć jest dealokowana po zakończeniu `move_a_box`.
Dlatego:
* Odczytanie `b` przez `println` po `move_a_box` jest niezdefiniowanym zachowaniem, ponieważ odczytuje zwolnioną pamięć.
* Nadanie `b` drugiego właściciela jest niezdefiniowanym zachowaniem, ponieważ Rust zwolniłby box po raz drugi w imieniu `b2`. Nie ma znaczenia, czy wiązanie `let b2 = b` następuje
  przed `move_a_box`, czy po nim.

Natomiast wykonanie `let b2 = b`, a potem `println` nie jest niezdefiniowanym zachowaniem. Choć `b` zostało przeniesione, jego dane nie są dealokowane, dopóki na końcu nie zostanie wywołane `move_a_box`. Dlatego 
ten program jest technicznie bezpieczny, choć Rust i tak go odrzuca.
"""
