[[questions]]
id = "7fbda6e4-dca7-458e-ab52-fab03181f90b"
type = "MultipleChoice"
prompt.prompt = """
Przyjrzyj się zmiennym `s2` i `s3` w poniższym programie. Obie zmienne znajdą się w pamięci w ramce stosu funkcji `main`. Każda zmienna zajmuje na stosie określony rozmiar, *nie* licząc rozmiaru wskazywanych danych. Które zdanie o rozmiarach `s2` i `s3` jest prawdziwe?

```
fn main() {
  let s = String::from("hello");
  let s2: &String = &s;
  let s3: &str = &s[..];
}
```
"""
answer.answer = "`s3` zajmuje więcej bajtów niż `s2`"
prompt.distractors = [
  "`s3` zajmuje tyle samo bajtów co `s2`",
  "`s3` zajmuje mniej bajtów niż `s2`"
]
context = """
Typ `&String` to zwykła referencja składająca się z jednego wskaźnika, więc na architekturze 64-bitowej zajmuje 8 bajtów. Typ `&str` to specjalna referencja będąca wycinkiem, która składa się ze wskaźnika *i* długości, więc zajmuje 16 bajtów. Dlatego `s3` typu `&str` zużywa więcej pamięci niż `s2` typu `&String`. Możesz to sprawdzić samodzielnie za pomocą [`std::mem::size_of`](https://doc.rust-lang.org/std/mem/fn.size_of.html), na przykład tak:

```rust
fn main() {
  println!(
    "&String={} &str={}",
    std::mem::size_of::<&String>(),
    std::mem::size_of::<&str>(),
  );
}
```

Zwróć też uwagę, że Rust niejawnie przekształca referencje do łańcuchów w `&String` albo `&str` w zależności od kontekstu referencji. Wyrażenie `&s` daje więc dwie różne wartości w zależności od oczekiwanego typu `&s`.
"""

[[questions]]
id = "adcfc154-03bd-470a-bacb-b3cad97cfc7f"
type = "Tracing"
prompt.program = """
fn main() {
  let mut s = String::from("hello");
  for &item in s.as_bytes().iter() {
    if item == b'l' {
      s.push_str(" world");
    }
  }
  println!("{s}");
}
"""
answer.doesCompile = false
answer.lineNumber = 5
context = """
Ponieważ `s.as_bytes()` tworzy niemutowalną referencję do `s`, modyfikowanie `s` (przez `push_str`) wewnątrz pętli for jest niedozwolone.
"""
