[[questions]]
id = "8c9f9173-c5ba-4914-9cfa-e3432f8414e1"
type = "MultipleChoice"
prompt.prompt = """
Który z poniższych sposobów NIE jest poprawnym rozwiązaniem problemu zwracania z funkcji referencji do stosu?
"""
answer.answer = "Wydłużenie czasu życia ramki stosu"
prompt.distractors = ["Użycie wskaźnika ze zliczaniem referencji", "Przejęcie własności zwracanej wartości", "Oczekiwanie od wywołującego mutowalnego miejsca na wynik"]
context = """
Czasu życia ramki stosu nie da się wydłużyć, więc nie jest to poprawne rozwiązanie.
"""

[[questions]]
id = "e6bc84ef-069c-4d1d-99ec-69b13492569c"
type = "MultipleChoice"
prompt.prompt = """
Załóżmy, że programista próbował napisać następującą funkcję:

```
/// Returns a person's name with "Ph.D." added as a title
fn award_phd(name: &String) -> String {
    let mut name = *name;
    name.push_str(", Ph.D.");
    name
}
```

Kompilator Rusta odrzuca ten kod z następującym błędem:

```text
error[E0507]: cannot move out of `*name` which is behind a shared reference
 --> test.rs:3:20
  |
3 |     let mut name = *name;
  |                    ^^^^^
  |                    |
  |                    move occurs because `*name` has type `String`, which does not implement the `Copy` trait
  |                    help: consider borrowing here: `&*name`
```

Biorąc pod uwagę opisany cel funkcji, która z poniższych poprawek programu byłaby najbardziej idiomatyczna?
Różnice względem powyższej funkcji są wyróżnione.
"""
answer.answer = """
```
fn award_phd(name: &String) -> String {
    let mut name = `[name.clone()]`;
    name.push_str(", Ph.D.");
    name
}
```
"""
prompt.distractors = [
"""
```
fn award_phd(name: &String) -> String {
    let mut name = `[&*name]`;
    name.push_str(", Ph.D.");
    name
}
```
""",
"""
```
fn award_phd(`[mut name: String]`) -> String {
    name.push_str(", Ph.D.");
    name
}
```
""",
"""
```
fn award_phd(`[name: &mut String]`) {
    name.push_str(", Ph.D.");
}
```
"""
]
context = """
Funkcja nie ma zmieniać pierwotnego imienia i nazwiska, więc zmiana typu `name` na `&mut String` albo na `String`
byłaby niewłaściwa. Rozwiązanie zaproponowane przez kompilator, czyli `&*name`, nie wystarcza – dopuszczalnym rozwiązaniem jest
sklonowanie danych za pomocą `name.clone()` i modyfikowanie lokalnej kopii.
"""

[[questions]]
id = "8020e4a2-f0b4-4eae-90ac-a87712d9d00b"
type = "MultipleChoice"
prompt.prompt = """
Załóżmy, że programista próbował napisać następującą funkcję:

```
/// Rounds all the floats in a vector to the nearest integer, in-place
fn round_in_place(v: &Vec<f32>) {
    for n in v {
        *n = n.round();
    }
}
```

Kompilator Rusta odrzuca ten kod z następującym błędem:

```text
error[E0594]: cannot assign to `*n`, which is behind a `&` reference
 --> test.rs:4:9
  |
3 |     for n in v {
  |              - this iterator yields `&` references
4 |         *n = n.round();
  |         ^^^^^^^^^^^^^^ `n` is a `&` reference, so the data it refers to cannot be written
```

Biorąc pod uwagę opisany cel funkcji, która z poniższych poprawek programu byłaby najbardziej idiomatyczna?
Różnice względem powyższej funkcji są wyróżnione.
"""
answer.answer = """
```
fn round_in_place(v: `[&mut Vec<f32>]`) {
    for n in v {
        *n = n.round();
    }
}
```
"""
prompt.distractors = [
"""
```
fn round_in_place(v: &Vec<f32>) `[-> Vec<f32>]` {
    `[let mut v2 = Vec::new();]`
    for n in v {
        `[v2.push(n.round());]`
    }
    `[v2]`
}
```
""",
"""
```
fn round_in_place(`[mut v: Vec<f32>]`) {
    for n in v {
        *n = n.round();
    }    
}
```
""",
"""
```
fn round_in_place(v: &Vec<f32>) {
    for `[mut n]` in `[&mut v.clone()]` {
        n = n.round();
    }    
}
```
""",
]
context = """
Ta funkcja ma zaokrąglać wektor w miejscu, więc zwracanie nowej kopii tego
samego wektora (`-> Vec<f32>`) albo przejmowanie własności wektora
(`mut v: Vec<f32>`) nie byłoby idiomatyczne. Najlepszym rozwiązaniem jest zmiana
sygnatury typu z `&Vec<f32>` na `&mut Vec<f32>`.
"""
