[[questions]]
id = "0b8dbb4f-7c56-4b6e-8358-95c7b46f90c3"
type = "ShortAnswer"
prompt.prompt = """
Rozważ poniższy program, który pokazuje stan pamięci po ostatniej linii:
```aquascope,interpreter
#fn main() {
let x = Box::new(0);
let y = Box::new(&x);`[]`
#}
```

Ilu dereferencji trzeba użyć, by skopiować liczbę `0` przez `y`?
Podaj odpowiedź jako cyfrę. Na przykład jeśli poprawnym wyrażeniem jest `*y`, odpowiedzią jest 1.
"""
answer.answer = "3"
context = """
Poprawnym wyrażeniem jest `***y`. `y` ma typ `Box<&Box<i32>>`. Jest to wskaźnik na stertę wskazujący na referencję na stosie,
która wskazuje na wskaźnik na stertę. Dlatego dereferencję `y` trzeba wykonać trzy razy, raz dla każdego poziomu pośredniości.
"""

[[questions]]
id = "7cf19153-3647-4afc-953a-f9392ddb96fb"
type = "MultipleChoice"
prompt.prompt = """
Rozważ poniższy program, który pokazuje stan pamięci po ostatniej linii:

```aquascope,interpreter
fn get_first(vr: &Vec<i32>) -> i32 {
  vr[0]
}

fn main() {
  let mut v = vec![0, 1, 2];
  let n = get_first(&v);
  println!("{} {}", n, v[1]);`[]` 
}
```

Które z poniższych zdań najlepiej wyjaśnia, dlaczego `v` nie zostaje zdealokowane po wywołaniu `get_first`?
"""
answer.answer = "`vr` jest referencją, która nie jest właścicielem wektora, na który wskazuje"
prompt.distractors = [
  "`vr` nie jest modyfikowane w `get_first`",
  "`get_first` zwraca wartość typu `i32`, a nie sam wektor",
  "`v` jest używane po wywołaniu `get_first` w `println`"
]
context = """
Referencje to wskaźniki, które nie są właścicielami. Dlatego przekazanie `&v` do `get_first` nie przenosi własności `v` do `get_first`,
a w konsekwencji `v` nie zostaje zdealokowane po zakończeniu `get_first`.
"""