[[questions]]
id = "1ec0098c-c5dc-46de-a889-b6659c0af757"
type = "MultipleChoice"
prompt.prompt = """
Załóżmy, że piszesz funkcję zgodnie z następującą specyfikacją:

> `round_all` przyjmuje listę liczb zmiennoprzecinkowych i zaokrągla każdą z nich w miejscu do najbliższej liczby całkowitej.

Która z poniższych sygnatur typu najlepiej pasuje do funkcji realizującej tę specyfikację?
"""
answer.answer = """
```
fn round_all(v: &mut Vec<f32>);
```
"""
prompt.distractors = [
"""
```
fn round_all(v: &Vec<f32>) -> Vec<f32>;
```
""",
"""
```
fn round_all(v: Vec<f32>);
```
""",
"""
```
fn round_all(v: &Vec<f32>);
```
"""
]
context = """
Specyfikacja wymaga modyfikowania danych wejściowych w miejscu, dlatego najodpowiedniejsza sygnatura przyjmuje mutowalną referencję do danych wejściowych.
Zarówno niemutowalna referencja, jak i wektor przekazany na własność nie pasują do tej specyfikacji.
"""

[[questions]]
id = "f8ca5ab2-0e5d-4c0d-bca2-99e6763ba9c5"
type = "MultipleChoice"
prompt.prompt = """
Załóżmy, że piszesz funkcję zgodnie z następującą specyfikacją:

> `find_contains` przyjmuje kolekcję łańcuchów znaków i szukany podłańcuch.
> Zwraca listę wszystkich łańcuchów z kolekcji, które zawierają szukany podłańcuch.

Która z poniższych sygnatur typu najlepiej pasuje do funkcji realizującej tę specyfikację?
"""
answer.answer = """
```
fn find_contains(haystack: &[String], needle: &str) -> Vec<&String>;
```
"""
prompt.distractors = [
"""
```
fn find_contains(haystack: &Vec<String>, needle: String) -> Vec<String>;
```
""",
"""
```
fn find_contains(haystack: &[String], needle: &str) -> Vec<String>;
```
""",
"""
```
fn find_contains(haystack: &Vec<String>, needle: &str) -> &[String];
```
"""
]
context = """
W przypadku `haystack` typ wycinka `&[String]` przyjmuje więcej rodzajów danych wejściowych niż `&Vec<String>`, dlatego jest lepszy.
W przypadku `needle` szukany podłańcuch nie musi być zaalokowany na stercie, więc `&str` jest lepszy niż `String`.
Jako typ zwracany `Vec<String>` nie jest pożądany, bo wymagałby sklonowania łańcuchów wejściowych.
`&[String]` nie jest pożądany, bo może zwrócić tylko ciągły fragment danych wejściowych.
`Vec<&String>` jest najlepszy, bo wiąże się tylko z kosztem alokacji wektora, a nie samych łańcuchów.
"""

[[questions]]
id = "868a4edf-16f0-4191-8aed-835c812b8b25"
type = "MultipleChoice"
prompt.prompt = """
Rust normalnie nie pozwala na wiele mutowalnych dostępów do tej samej tablicy, nawet jeśli dotyczą one rozłącznych fragmentów.
Na przykład ta funkcja się nie kompiluje:

```
fn main() {
  let mut v = vec![0, 1, 2, 3];
  let (r0, r1) = (&mut v[0..2], &mut v[2..4]);
  r0[0] += 1;
  r1[0] += 1;  
}
```

Biblioteka standardowa Rusta ma jednak funkcję `slice::split_at_mut`, która na to pozwala:

```
fn main() {
  let mut v = vec![0, 1, 2, 3];
  let (r0, r1) = v.split_at_mut(2);
  r0[0] += 1;
  r1[0] += 1;  
}
```

Które z poniższych zdań najlepiej opisuje, jak można zaimplementować `split_at_mut`?
"""
answer.answer = "`split_at_mut` używa niebezpiecznego kodu, by obejść borrow checker za pomocą surowych wskaźników"
prompt.distractors = [
"`split_at_mut` to specjalna wbudowana operacja kompilatora, której nie da się zaimplementować w samym języku",
"`split_at_mut` używa niebezpiecznego kodu, by wyłączyć sprawdzanie bezpieczeństwa mutowalnych referencji przez borrow checker",
"`split_at_mut` wywołuje bibliotekę napisaną w C, której Rust nie potrafi przeanalizować"
]
context = """
Jak omówiliśmy w [podrozdziale 4.3, „Naprawianie bezpiecznego programu: modyfikowanie różnych elementów tablicy”](ch04-03-fixing-ownership-errors.html#fixing-a-safe-program-mutating-different-array-elements), funkcje takie jak `split_at_mut` są zaimplementowane z użyciem mechanizmu `unsafe`.
Ten mechanizm nie wyłącza całkowicie borrow checkera, lecz pozwala korzystać z określonych niebezpiecznych funkcji, takich jak surowe wskaźniki.
"""


[[questions]]
id = "ba32e57a-e5f2-42e4-8cfd-eb265990c690"
type = "MultipleChoice"
prompt.prompt = """
Przyjrzyj się uprawnieniom w następującym programie:

```aquascope,permissions,boundaries,stepper
#fn main() {
let s = String::new();
let s_ref = &s;`(focus,paths:*s_ref)`
#println!("{s_ref}");
#}
```

Które z poniższych zdań najlepiej wyjaśnia, dlaczego `*s_ref` nie ma uprawnienia @Perm{own} (własność)?
"""
answer.answer = "Własność pozwala na przeniesienie, a przeniesienie danych z referencji może spowodować podwójne zwolnienie"
prompt.distractors = [
  "Własność pozwala na pożyczanie, a ponowne pożyczenie `*s_ref` może spowodować podwójne zwolnienie",
  "Własność pozwala na modyfikowanie, a modyfikacja `*s_ref` może spowodować użycie po zwolnieniu",
  "Własność pozwala na odczyt, a odczyt `*s_ref` może spowodować użycie po zwolnieniu"
]
context = """
Uprawnienie @Perm{own} oznacza własność obiektu. Obiekt może mieć tylko jednego właściciela, dlatego ważne jest,
by referencje nie mogły przekazywać własności typów, których nie da się kopiować, takich jak `String`. Gdyby dwie zmienne
uważały, że są właścicielami tego samego łańcucha, obie próbowałyby go zdealokować, co spowodowałoby podwójne zwolnienie.
"""

[[questions]]
id = "3a5f5de5-23a9-49fb-bdb4-acc9c3fbb4a6"
type = "MultipleChoice"
prompt.prompt = """
Rozważ zbiór programów w Ruście, które nie zawierają kodu `unsafe`.
Zaznacz wszystkie prawdziwe stwierdzenia o tym, jakie programy borrow checker akceptuje, a jakie odrzuca:
"""
answer.answer = [
  "Borrow checker zawsze odrzuca programy z niezdefiniowanym zachowaniem",
  "Borrow checker czasem odrzuca programy bez niezdefiniowanego zachowania",
]
prompt.distractors = [
  "Borrow checker zawsze akceptuje programy bez niezdefiniowanego zachowania",
  "Borrow checker czasem akceptuje programy z niezdefiniowanym zachowaniem"
]
context = """
Borrow checker zawsze odrzuca programy z niezdefiniowanym zachowaniem, ale czasem może odrzucić programy bez niezdefiniowanego zachowania (czyli całkowicie bezpieczne).
Mówiąc technicznie, borrow checker jest analizą poprawną (*sound*), ale niezupełną (*incomplete*).
"""


[[questions]]
id = "208e0e38-a706-4d96-9809-f0e12f574136"
type = "MultipleChoice"
prompt.prompt = """
Borrow checker odrzuca funkcję `extract`:

```rust
fn extract(b: &Box<i32>) -> i32 {
    let b2: Box<i32> = *b;
    *b2
}
```

Wyobraź sobie, że borrow checker nie odrzuca tej funkcji.
Ustal, czy istnieją dane wejściowe, dla których wykonanie tej funkcji spowodowałoby niezdefiniowane zachowanie.
"""
answer.answer = "Ta funkcja MOGŁABY spowodować niezdefiniowane zachowanie"
prompt.distractors = ["Ta funkcja NIE mogłaby spowodować niezdefiniowanego zachowania"]
context = """
Ta funkcja spowodowałaby podwójne zwolnienie dla dowolnych danych wejściowych.
"""


[[questions]]
id = "dcfd54f8-7fe6-4483-aefd-ea95ba5b5eb0"
type = "MultipleChoice"
prompt.prompt = """
Borrow checker odrzuca funkcję `transfer_string`:

```rust
fn get_first(strs: &mut (String, String)) -> &mut String {
    &mut strs.0
}

fn get_second(strs: &mut (String, String)) -> &mut String {
    &mut strs.1
}

fn transfer_string(strs: &mut (String, String)) {
    let fst = get_first(strs);
    let snd = get_second(strs);
    fst.push_str(snd);
    snd.clear();
}
```

Wyobraź sobie, że borrow checker nie odrzuca tej funkcji.
Ustal, czy istnieją dane wejściowe, dla których wykonanie tej funkcji spowodowałoby niezdefiniowane zachowanie.
"""
answer.answer = "Ta funkcja NIE mogłaby spowodować niezdefiniowanego zachowania"
prompt.distractors = ["Ta funkcja MOGŁABY spowodować niezdefiniowane zachowanie"]
context = """
Borrow checker odrzuca tę funkcję, ponieważ zakłada, że `get_first` i `get_second` mogą zwrócić mutowalną
referencję do dowolnego elementu krotki, więc `fst` i `snd` mogłyby wskazywać na tę samą wartość. W tym programie
są one jednak zawsze różne, więc funkcja jest w rzeczywistości bezpieczna.
"""



