[[questions]]
id = "cbe8ef63-4f7e-45fd-b11f-e6eba40587b0"
type = "MultipleChoice"
prompt.prompt = """
Które z poniższych najlepiej wyjaśnia, dlaczego `i32` można skopiować bez przenoszenia, a `String` nie?
"""
answer.answer = "`String` posiada dane na stercie, a `i32` nie"
prompt.distractors = [
    "`i32` zajmuje w pamięci mniej miejsca niż `String`",
    "`i32` jest w Ruście typem prymitywnym, a `String` nie",
    "`String` może zostać umieszczony na stercie, a `i32` tylko na stosie"
]
context = """
Gdyby `String` dało się skopiować bez przenoszenia, dwie zmienne mogłyby uważać, że są
właścicielami tego samego łańcucha, co prowadziłoby do podwójnego zwolnienia.
"""

[[questions]]
id = "512e1ec0-cd7b-4a90-949b-d7b08b4009a8"
type = "MultipleChoice"
prompt.prompt = """
Poniższy fragment kodu się nie kompiluje:

```rust
let s = String::from("Hello world");
let s_ref = &s;
let s2 = *s_ref;
println!("{s2}");
```

Które z poniższych najlepiej opisuje niezdefiniowane zachowanie, do którego mogłoby dojść, gdyby pozwolono wykonać ten program?
"""
answer.answer = "Łańcuch zostaje zwolniony dwukrotnie na końcu programu"
prompt.distractors = [
  "Odczyt `s2` w `println` jest użyciem zwolnionej pamięci",
  "Dereferencja `*s_ref` jest użyciem zwolnionej pamięci",
  "W tym programie nie ma niezdefiniowanego zachowania"
]
context = """
Samo `println` jest formalnie bezpieczne, ponieważ łańcuch zostanie zdealokowany dopiero na końcu
bieżącego zasięgu. Wtedy jednak dochodzi do niezdefiniowanego zachowania, bo łańcuch jest zwalniany
dwukrotnie: raz w imieniu `s`, a raz w imieniu `s2`.
"""

[[questions]]
id = "1e31e163-5bd4-4385-b222-33c19058bf6a"
type = "MultipleChoice"
prompt.prompt = """
Poniższy program się nie kompiluje:

```rust
fn copy_to_prev(v: &mut Vec<i32>, i: usize) {
  let n = &mut v[i];
  *n = v[i - 1];
}
fn main() {
  let mut v = vec![1, 2, 3];
  copy_to_prev(&mut v, 1);
}
```

Które z poniższych najlepiej opisuje niezdefiniowane zachowanie, do którego mogłoby dojść, gdyby pozwolono wykonać ten program?
"""
answer.answer = "W tym programie nie ma niezdefiniowanego zachowania"
prompt.distractors = [
  "Przypisanie do `*n` jest użyciem zwolnionej pamięci",
  "Pożyczenie `&mut v[i]` tworzy wskaźnik do zwolnionej pamięci",
  "Odczyt `v[i - 1]` jest użyciem zwolnionej pamięci"
]
context = """
Ten program jest bezpieczny. Jego wykonanie nie mogłoby doprowadzić do niezdefiniowanego zachowania. (Gdyby `i` wykraczało
poza granice `v`, Rust spanikowałby w czasie działania, zamiast doprowadzić do niezdefiniowanego zachowania).

Problem polega na tym, że Rust nie wie na pewno, że `v[i]` i `v[i - 1]` odnoszą się do różnych elementów.
"""


[[questions]]
id = "4df75888-2cd5-4259-8629-46a307429fd0"
type = "MultipleChoice"
prompt.prompt = """
Rozważ tę funkcję, która jest uproszczoną wersją funkcji z poprzedniego quizu:

```
/// Adds "Ph.D." to a person's name
fn award_phd(name: &String) {
    let mut name = *name;
    name.push_str(", Ph.D.");
}
```

Kompilator Rusta odrzuca tę funkcję z następującym błędem:

```text
error[E0507]: cannot move out of `*name` which is behind a shared reference
 --> test.rs:3:20
  |
3 |     let mut name = *name;
  |                    ^^^^^
  |                    |
  |                    move occurs because `*name` has type `String`, which does not implement the `Copy` trait
  |                    help: consider borrowing here: `&*name`
```

Załóż, że kompilator NIE odrzucił tej funkcji. Zaznacz każdy z poniższych programów (jeśli taki jest), który po wykonaniu
mógłby spowodować niezdefiniowane zachowanie. Jeśli żaden z tych programów nie mógłby spowodować niezdefiniowanego zachowania,
zaznacz „Żaden z tych programów”.
"""
answer.answer = [
"""
```
let name = String::from("Ferris");
award_phd(&name);
```
""",
"""
```
let name = String::from("Ferris");
award_phd(&name);
println!("{}", name);
```
""",
"""
```
let name = String::from("Ferris");
let name_ref = &name;
award_phd(&name);
println!("{}", name_ref);
```
""",

]
prompt.distractors = [
  "Żaden z tych programów"
]
context = """
Instrukcja `let mut name = *name` sprawia, że `name` przejmuje własność wejściowego łańcucha.
Wywołujący nadal jednak zachowuje własność tego łańcucha. Dlatego po zakończeniu `award_phd`
łańcuch zostaje zdealokowany. W efekcie każdy z powyższych programów ma niezdefiniowane zachowanie,
ponieważ `name` w końcu zostanie zdealokowane po raz drugi. Nie ma znaczenia, czy po wywołaniu
`award_phd` odczytywane jest `name`, czy referencja do `name`.
"""

[[questions]]
id = "1f48fda5-afc6-440b-a9aa-53dc8d54efaa"
type = "Tracing"
prompt.program = """
fn main() {
    let mut point = [0, 1];
    let mut x = point[0];
    let y = &mut point[1];
    x += 1;
    *y += 1;
    println!("{} {}", point[0], point[1]);
}
"""
answer.doesCompile = true
answer.stdout = "0 2"
context = """
Ten program się kompiluje, ponieważ wiązanie `x` kopiuje `point[0]`, co pozwala `y` mutowalnie pożyczyć `point[1]`.
Modyfikacja `x += 1` nie wpływa na `point`, a modyfikacja `*y += 1` już tak, więc wynikiem jest `0 2`.
"""