[[questions]]
id = "5d774a01-8604-4386-8d81-498496ccd96c"
type = "MultipleChoice"
prompt.prompt = """
Które z poniższych zdań najlepiej opisuje różnicę między stosem a stertą?
"""
answer.answer = "Stos przechowuje dane związane z konkretną funkcją, a sterta przechowuje dane, które mogą żyć dłużej niż funkcja"
prompt.distractors = [ 
  "Stos może przechowywać wskaźniki na dane na stercie, a sterta przechowuje tylko dane bez wskaźników",
  "Stos przechowuje dane niemutowalne, a sterta przechowuje dane mutowalne.",
  "Stos przechowuje dane, które można kopiować, a sterta dane, których nie można kopiować."
]
context = """
Ramki na stosie są związane z konkretną funkcją i są dealokowane, gdy funkcja się kończy.
Dane na stercie mogą żyć dowolnie długo. Zauważ, że zarówno dane na stosie, jak i na stercie mogą być mutowalne i kopiowalne. Sterta może
zawierać wskaźniki (nawet na stos, jak zobaczymy później).
"""

[[questions]]
id = "4c953b2d-65bf-4dab-bbbb-14c9b15a690e"
type = "ShortAnswer"
prompt.prompt = """
Rozważ wykonanie poniższego fragmentu kodu; pokazany jest stan końcowy:

```aquascope,interpreter
#fn main() {
let a = Box::new(15);
let b = a;
let c = Box::new(15);`[]`
#}
```

Ile kopii liczby `15` znajduje się gdziekolwiek w pamięci w stanie końcowym? Wpisz odpowiedź jako cyfrę, np. 0 albo 1.
"""
answer.answer = "2"
context = """
Dwie kopie liczby 15 znajdują się w dwóch boxach. Przypisanie `let b = a` kopiuje wskaźnik na stertę, ale nie liczbę na stercie.
"""
