[[questions]]
id = "ae4e06f6-5fdc-43d9-929c-85eba3559a82"
type = "MultipleChoice"
prompt.prompt = "Jakie jest w Ruście słowo kluczowe dla konstruktorów?"
answer.answer = "Żadne z powyższych"
prompt.distractors = [
  "`constructor`",
  "`new`",
  "Nazwa konstruowanego typu",
]
prompt.answerIndex = 3
context = """
Rust nie ma słowa kluczowego dla konstruktorów. Idiomatycznym sposobem zdefiniowania konstruktora jest utworzenie funkcji powiązanej o nazwie `new`, 
ale język tego nie wymusza.
"""

[[questions]]
id = "a506f97d-2b51-4517-bc4d-f69764093c71"
type = "Tracing"
prompt.program = """
struct Point(i32, i32);
fn main() {
  let p = Point(1, 2);

  impl p {
    fn x(&self) -> i32 { self.0 }
  }
  
  println!("{}", p.x());
}
"""
answer.doesCompile = false
answer.lineNumber = 5
context = """ 
Metody można implementować tylko dla typów (np. `impl Point`), a nie dla zmiennych (takich jak `p`).
"""