[[questions]]
id = "f0ec64fa-262f-4819-8379-acad7aaf8be2"
type = "Tracing"
prompt.program = """
#[derive(Debug)]
struct Rectangle {
  width: u32,
  height: u32,
}

fn main() {
  let rect1 = Rectangle {
    width: 30,
    height: 50,
  };

  let a = area(rect1);
  println!("{} * {} = {}", rect1.width, rect1.height, a);
}

fn area(rectangle: Rectangle) -> u32 {
  rectangle.width * rectangle.height
}
"""
answer.doesCompile = false
answer.lineNumber = 14
context = """ 
Funkcja `area` przejmuje własność swojego argumentu `rectangle`. Wywołanie `area(rect1)` przenosi więc
`rect1`, co oznacza, że nie można go użyć w następnej linii.
"""

[[questions]]
id = "9ce4156e-4112-4101-a2c7-51758ceca639"
type = "MultipleChoice"
prompt.prompt = "Które stwierdzenie najlepiej opisuje różnicę między traitami `Display` i `Debug`?"
answer.answer = "`Display` służy do prezentowania wartości użytkownikowi końcowemu, a `Debug` do wewnętrznego użytku programistów"
prompt.distractors = [
  "`Display` służy do wypisywania wartości w konsoli, a `Debug` do podglądania wartości w debugerze",
  "`Display` nie może być zaimplementowany dla struktur, a `Debug` może",
  "Nie ma różnicy, `Display` i `Debug` to aliasy tego samego traitu."
]
