[[questions]]
id = "97781ca8-ad58-449c-9769-e20b9d2e42a6"
type = "MultipleChoice"
prompt.prompt = """
Załóżmy, że masz zmienną `v` typu `&mut Vec<i32>` i chcesz wywołać metodę `len` o następującej
sygnaturze:

```
impl Vec<i32> {
  fn len(&self) -> usize {
    /* ... */
  }
}
```

Które z poniższych stwierdzeń najlepiej opisuje, co się stanie, gdy spróbujesz skompilować wyrażenie `v.len()`?
"""
answer.answer = "Kompiluje się, bo referencja `&mut` jest niejawnie ponownie pożyczana jako referencja `&`"
prompt.distractors = [
  "Nie kompiluje się, bo `&mut Vec<i32>` to nie ten sam typ co `&Vec<i32>`",
  "Nie kompiluje się, bo na `v` nie wykonano jawnie dereferencji",
  "Kompiluje się, bo `&self` może przyjąć referencję dowolnego rodzaju"
]
context = """
Wyrażenie `v.len()` po usunięciu lukru składniowego to `Vec::len(&*v)`, czyli poprawne ponowne pożyczenie `v`, więc to wyrażenie się kompiluje.
Nie można jednak przekazać `v` bezpośrednio do `Vec::len`, bo `&self` oznacza konkretnie referencje niemutowalne.
"""

[[questions]]
id = "35a75881-eb08-486c-92b3-413ab512138a"
type = "MultipleChoice"
prompt.prompt = """
Rozważ te dwie metody, które zwiększają pole struktury. Który styl jest bardziej idiomatyczny w Ruście?

```
struct Point(i32, i32);
impl Point {
  fn incr_v1(mut self)  { self.0 += 1; }
  fn incr_v2(&mut self) { self.0 += 1; }
}
```
"""
answer.answer = "`incr_v2`"
prompt.distractors = [
  "`incr_v1`",
  "Oba są idiomatyczne",
  "Żaden nie jest idiomatyczny"
]
prompt.answerIndex = 1
context = """
Metoda `incr_v1` nie jest idiomatyczna, bo przejmuje własność `Point`. Oznacza to, że po wywołaniu `p.incr_v1()` zmiennej `p` 
nie dałoby się już używać, a raczej nie o to chodzi w tej metodzie.
"""

[[questions]]
id = "03a0a1ec-8ce6-40f2-b8b7-6dd5402aeb7d"
type = "Tracing"
prompt.program = """
struct Point(i32, i32);
impl Point {
  fn incr_x(&mut self) {
    self.0 += 1;
  }
}

fn main() {
  let mut p = Point(0, 0);
  p.incr_x();
  println!("{}", p.0);
}
"""
answer.doesCompile = true
answer.stdout = "1"
context = """ 
Pamiętaj, że `.0` jest poprawne dla struktur krotkowych, takich jak `Point`.
"""

[[questions]]
id = "be7be598-8a31-4c1a-9171-4ff90f512430"
type = "Tracing"
prompt.program = """
struct Point {
  x: i32,
  y: i32
}

impl Point {
  fn get_x(&mut self) -> &mut i32 {
    &mut self.x
  }
}

fn main() {
  let mut p = Point { x: 1, y: 2 };
  let x = p.get_x();
  *x += 1;
  println!("{} {}", *x, p.y);
}
"""
answer.doesCompile = false
answer.lineNumber = 16
context = """ 
Ponieważ `get_x` mutowalnie pożycza całe `p`, program nie może w żaden sposób używać `p`, dopóki `x` jest jeszcze używane. 
Dlatego odczyt `x` i `p.y` w tej samej linii jest błędem własności.
"""