[[questions]]
id = "770f09d3-110d-4505-b41a-2af422198d59"
type = "Tracing"
prompt.program = """
fn foo(x: &i32) { 
  println!("{x}");
}

fn main() {
  let x = null;
  foo(x);
}
"""
answer.doesCompile = false
answer.lineNumber = 6
context = """ 
Rust nie ma wskaźników null, więc słowo kluczowe `null` nie istnieje. Do wyrażenia tego, że obiekt może być null, należy użyć typu Option.
"""

[[questions]]
id = "6226be11-31c3-4cac-b97c-515514a70af2"
type = "MultipleChoice"
prompt.prompt = """
Rozważ dwie reprezentacje typu `Result`, który zawiera wartość `T`, jeśli obliczenie się powiedzie, albo błąd `E`, jeśli się nie powiedzie.

```
struct Result1<T, E> {
  ok: Option<T>,
  err: Option<E>,
}

enum Result2<T, E> {
  Ok(T),
  Err(E)
}
```

W Ruście enum `Result2` uważa się za bardziej idiomatyczny niż strukturę `Result1`. 
Które z poniższych stwierdzeń **NIE** jest prawidłowym uzasadnieniem?
"""
answer.answer = "Struktura zawiera typy `Option`, które są przeznaczone wyłącznie do opakowywania struktur"
prompt.distractors = [
  "W czasie działania struktura zajmuje więcej pamięci niż enum",
  "W strukturze zarówno `ok`, jak i `err` mogą być `None`, a enum musi mieć przynajmniej jedno z nich",
  "Tworzenie struktury wymaga rozwleklejszej składni niż tworzenie enuma"
]
context = """
Struktury jak najbardziej mogą zawierać pola typu `Option` (pytanie dotyczyło tego, co **NIE** jest prawidłowym uzasadnieniem).
Jeśli jednak twoja struktura danych ma niezmienniki takie jak „dokładnie jedno z dwóch opcjonalnych pól powinno być `Some`”,
to lepiej zapewnić taki niezmiennik za pomocą enuma.
"""


