[[questions]]
id = "6e5e193e-579d-4a46-aae4-d35336b77b68"
type = "MultipleChoice"
prompt.prompt = """
**Program 1:**

```ide
/// Makes a string to separate lines of text, 
/// returning a default if the provided string is blank
fn make_separator(user_str: &str) -> &str {
    if user_str == "" {
        let default = "=".repeat(10);
        &default
    } else {
        user_str
    }
}
```

Które z poniższych najlepiej opisuje błąd, jaki zgłosiłby kompilator przy próbie skompilowania tej funkcji?
"""
answer.answer = "nie można zwrócić referencji do zmiennej lokalnej `default`"
prompt.distractors = [
  "`user_str` nie żyje wystarczająco długo",
  "funkcja `make_separator` nie może zwrócić referencji typu `&str`",
  "funkcja `make_separator` nie może zwrócić dwóch różnych referencji"
]
context = """
Ponieważ `default` żyje na stosie wewnątrz `make_separator`, zostanie zdealokowane, gdy wywołanie `make_separator` się zakończy.
Wtedy `&default` wskazuje na zdealokowaną pamięć. Dlatego Rust zgłasza, że nie można zwrócić referencji do zmiennej lokalnej.
"""

[[questions]]
id = "44a2eb01-b49a-497b-a9d2-207814d1db1e"
type = "MultipleChoice"
prompt.prompt = """
**Program 1:**

```ide
/// Makes a string to separate lines of text, 
/// returning a default if the provided string is blank
fn make_separator(user_str: &str) -> &str {
    if user_str == "" {
        let default = "=".repeat(10);
        &default
    } else {
        user_str
    }
}
```

Normalnie przy próbie skompilowania tej funkcji kompilator zwraca następujący błąd:

```text
error[E0515]: cannot return reference to local variable `default`
 --> test.rs:6:9
  |
6 |         &default
  |         ^^^^^^^^ returns a reference to data owned by the current function
```

Załóż, że kompilator NIE odrzucił tej funkcji. Które z poniższych programów (jeśli w ogóle jakieś)
(1) przeszłyby przez kompilator i (2) mogłyby spowodować niezdefiniowane zachowanie po wykonaniu?
Zaznacz każdy program, który spełnia oba kryteria, ALBO zaznacz „Żaden z tych programów”, jeśli żaden ich nie spełnia.
"""
answer.answer = ["""
```
let s = make_separator("");
println!("{s}");
```
"""]
prompt.distractors = [
"""
```
println!("{}", make_separator("Hello world!"));
```
""",
"Żaden z tych programów",
]
context = """
Wywołujący musi przekazać pusty łańcuch, aby spełnić problematyczny warunek instrukcji if. Wtedy funkcja zwraca wiszący wskaźnik.
"""

[[questions]]
id = "815ae4cd-0f23-4da5-9dc2-0e81c664cc28"
type = "MultipleChoice"
prompt.prompt = """
**Program 1:**

```ide
/// Makes a string to separate lines of text, 
/// returning a default if the provided string is blank
fn make_separator(user_str: &str) -> &str {
    if user_str == "" {
        let default = "=".repeat(10);
        &default
    } else {
        user_str
    }
}
```

Która z poniższych poprawek (wyróżnionych na żółto) najlepiej spełnia te trzy kryteria:
1. Poprawiona funkcja przechodzi przez kompilator Rusta;
2. Poprawiona funkcja zachowuje intencję oryginalnego kodu;
3. Poprawiona funkcja nie wprowadza zbędnej nieefektywności.
"""
answer.answer = """
```ide
fn make_separator(user_str: &str) -> `[String]` {
    if user_str == "" {
        let default = "=".repeat(10);
        `[default]`
    } else {
        `[user_str.to_string()]`        
    }
}
```
"""
prompt.distractors = [
"""
```ide
fn make_separator(user_str: &str) -> &str {
    if user_str == "" {
        let default = "=".repeat(10);
        &default
    } else {
        `[&user_str]`
    }
}
```
""",
"""
```ide
fn make_separator(user_str: `[String]`) -> `[String]` {
    if user_str == "" {
        let default = "=".repeat(10);
        `[default]`
    } else {
        user_str
    }
}
```
""",
]
context = """
Nie ma poprawnego sposobu na zwrócenie wskaźnika do zmiennej zaalokowanej na stosie. Proste rozwiązanie polega więc na zmianie typu zwracanego na `String`
i skopiowaniu wejściowego `user_str` do łańcucha, który jest właścicielem swoich danych. Wymaganie, by `user_str` było typu `String`, ograniczyłoby jednak elastyczność API, np.
wywołujący nie mógłby wywołać `make_separator` na podłańcuchu większego łańcucha. Wymagałoby też od wywołujących alokowania łańcuchów na stercie, np.
nie mogliby użyć literału łańcuchowego, jak w `make_separator("Rust")`.

Najbardziej idiomatyczne rozwiązanie tego problemu korzysta z konstrukcji, której jeszcze nie znasz: [`Cow`](https://doc.rust-lang.org/std/borrow/enum.Cow.html).
Ten inteligentny wskaźnik typu *clone-on-write* (klonowanie przy zapisie) pozwoliłby tej funkcji zwrócić *albo* łańcuch będący właścicielem swoich danych, *albo* referencję do łańcucha, bez błędu typu.
"""

[[questions]]
id = "1f4e5c06-ecdf-481d-9cae-8a25dafe9cfd"
type = "MultipleChoice"
prompt.prompt = """
**Program 2:**

```ide
/// Gets the string out of an option if it exists,
/// returning a default otherwise
fn get_or_default(arg: &Option<String>) -> String {
    if arg.is_none() {
        return String::new();
    }
    let s = arg.unwrap();
    s.clone()
}
```

Które z poniższych najlepiej opisuje błąd, jaki zgłosiłby kompilator przy próbie skompilowania tej funkcji?
"""
answer.answer = "nie można przenieść wartości z `arg` w `arg.unwrap()`"
prompt.distractors = [
  "nie można wywołać `arg.is_none()` bez dereferencji `arg`",
  "`arg` nie żyje wystarczająco długo",
  "nie można zwrócić `s.clone()`, które nie żyje wystarczająco długo"
]
context = """
Funkcja `Option::unwrap` przyjmuje `self`, czyli oczekuje własności `arg`. Jednak `arg` jest niemutowalną
referencją do opcji, więc nie może przekazać własności opcji. Dlatego kompilator zgłasza, że nie możemy
przenieść wartości z `arg` za pomocą `unwrap`.
"""


[[questions]]
id = "989670b2-b038-47c4-9975-a93d6ee193e5"
type = "MultipleChoice"
prompt.prompt = """
**Program 2:**

```ide
/// Gets the string out of an option if it exists,
/// returning a default otherwise
fn get_or_default(arg: &Option<String>) -> String {
    if arg.is_none() {
        return String::new();
    }
    let s = arg.unwrap();
    s.clone()
}
```

Normalnie przy próbie skompilowania tej funkcji kompilator zwraca następujący błąd:

```text
error[E0507]: cannot move out of `*arg` which is behind a shared reference
   --> test.rs:7:13
    |
7   |     let s = arg.unwrap();
    |             ^^^^--------
    |             |   |
    |             |   `*arg` moved due to this method call
    |             help: consider calling `.as_ref()` or `.as_mut()` to borrow the type's contents
    |             move occurs because `*arg` has type `Option<String>`, which does not implement the `Copy` trait
```

Załóż, że kompilator NIE odrzucił tej funkcji. Które z poniższych programów (jeśli w ogóle jakieś)
(1) przeszłyby przez kompilator i (2) mogłyby spowodować niezdefiniowane zachowanie po wykonaniu?
Zaznacz każdy program, który spełnia oba kryteria, ALBO zaznacz „Żaden z tych programów”, jeśli żaden ich nie spełnia.
"""
answer.answer = [
"""
```
let opt = Some(String::from("Rust"));
get_or_default(&opt);
println!("{:?}", opt);
```
""",
"""
```
let opt = Some(String::from("Rust"));
let s = get_or_default(&opt);
println!("{}", s);
```
""", 
"""
```
let opt = Some(String::from("Rust"));
get_or_default(&opt);
```
""", 
]
prompt.distractors = [
"Żaden z tych programów",
]
context = """
Wszystkie te programy naruszają bezpieczeństwo pamięci przez podwójne zwolnienie. Gdyby `arg.unwrap()` było dozwolone,
własność łańcucha `String::from("Rust")` przejęłoby `s`. Po powrocie z `get_or_default`
łańcuch zostałby zwolniony. Jednak `opt` również uważa się za właściciela tego łańcucha, więc
łańcuch zostałby zwolniony drugi raz w imieniu `opt`.
"""

[[questions]]
id = "3a8d5bb8-a204-43e6-b50a-d17c803dbe37"
type = "MultipleChoice"
prompt.prompt = """
**Program 2:**

```ide
/// Gets the string out of an option if it exists,
/// returning a default otherwise
fn get_or_default(arg: &Option<String>) -> String {
    if arg.is_none() {
        return String::new();
    }
    let s = arg.unwrap();
    s.clone()
}
```

Która z poniższych poprawek (wyróżnionych na żółto) najlepiej spełnia te trzy kryteria:
1. Poprawiona funkcja przechodzi przez kompilator Rusta;
2. Poprawiona funkcja zachowuje intencję oryginalnego kodu;
3. Poprawiona funkcja nie wprowadza zbędnej nieefektywności.
"""
answer.answer = """
```ide
fn get_or_default(arg: &Option<String>) -> String {
    `[match arg {]`
        `[None => String::new(),]`
        `[Some(s) => s.clone()]`
    `[}]`
}
```
"""
prompt.distractors = [
"""
```ide
fn get_or_default(arg: `[&mut Option<String>]`) -> String {
    if arg.is_none() {
        return String::new();
    }
    let s = arg`[.as_mut()]`.unwrap();
    s.clone()
}
```
""",
"""
```ide
fn get_or_default(arg: `[Option<String>]`) -> String {
    if arg.is_none() {
        return String::new();
    }
    let s = arg.unwrap();
    s.clone()
}
```
""",
"""
```ide
fn get_or_default(arg: &Option<`[&str]`>) -> String {
    if arg.is_none() {
        return String::new();
    }
    let s = arg.unwrap();
    `[s.to_string()]`
}
```
""",
]
context = """
Połączenie `is_none` i `unwrap` jest tu w Ruście antywzorcem, ponieważ `match` łączy obie te funkcje i
automatycznie „przepycha” referencję `&Option` do wnętrza, dając `&String`. Dlatego rozwiązanie z `match`
jest najbardziej idiomatyczne i przechodzi przez kompilator bez zmiany zamierzonej sygnatury typu funkcji.

Rozwiązanie polegające na zmianie `&Option` na `Option` nie jest pożądane, ponieważ wymaga od wywołującego przekazania własności jego opcji,
co daje znacznie bardziej restrykcyjne API.
"""