[[questions]]
id = "5b6e4016-c089-4cb3-96a7-ca9f88694488"
type = "Tracing"
prompt.program = """
enum Location {
  Point(i32),
  Range(i32, i32)
}

fn main() {
  let l: Location = Location::Range(0, 5);
  let n = match l {
    Location::Point(_) => -1,
    Location::Range(_, 5) => 5,
    Location::Range(0, _) => 0,
    _ => -2
  };
  println!("{n}");
}
"""
answer.doesCompile = true
answer.stdout = "5"
context = """ 
Wzorce są sprawdzane od góry do dołu. Pasują zarówno drugi, jak i trzeci wzorzec, więc użyty zostaje drugi.
"""


[[questions]]
id = "f7c361e0-733a-4d48-9809-736e3c1e2b67"
type = "MultipleChoice"
prompt.prompt = """
Rozważ tę metodę zaimplementowaną dla typu `Option`:

```
impl<T> Option<T> {
  fn unwrap_or(self, other: T) -> T {
    match self {
      Some(t) => t,
      None => other
    }
  }
}
```

Które zdanie najlepiej opisuje działanie tej funkcji?
"""
answer.answer = "Zwraca obiekt wewnątrz `self`, jeśli istnieje, a w przeciwnym razie `other`"
prompt.distractors = [
  "Zwraca nową opcję zawierającą obiekt wewnątrz `self`, jeśli istnieje, a w przeciwnym razie `other`",
  "Wstawia `other` do `self`, jeśli `self` nie zawiera jeszcze wartości",
  "Zwraca referencję do obiektu wewnątrz `self`, jeśli istnieje, a w przeciwnym razie `other`"
]
context = """
Ta funkcja „rozpakowuje” opcję: przejmuje ją na własność i wydobywa wartość ze środka, a jeśli wartości nie ma, awaryjnie zwraca `other`.
To prawdziwa funkcja z biblioteki standardowej!
"""


[[questions]]
id = "1e4f082c-ffa4-4d33-8726-2dbcd72e1aa2"
type = "Tracing"
prompt.program = """
#[derive(Debug)]
enum Either {
  Left(usize),
  Right(String)
}

fn main() {
  let x = Either::Right(String::from("Hello world"));
  let value = match x {
    Either::Left(n) => n,
    Either::Right(s) => s.len()
  };
  println!("{x:?} {value}");
}
"""
answer.doesCompile = false
answer.lineNumber = 13
context = """
Ramię `Either::Right(s)` przenosi pole `s`, więc `x` nie można użyć w `println`.
"""


[[questions]]
id = "6e012d34-5c59-443e-85d9-385f0d7dee13"
type = "MultipleChoice"
prompt.prompt = """
Rozważ dwie implementacje funkcji, która dwukrotnie zmniejsza o 1 liczbę bez znaku.

```
fn decr_twice_v1(n: u32) -> Option<u32> {
  match n {
    0 => None,
    1 => None,
    n2 => Some(n2 - 2)
  }
}

fn decr_twice_v2(n: u32) -> Option<u32> {
  if n == 0 {
    None
  } else if n == 1 {
    None
  } else {
    Some(n - 2)
  }
}
```

Funkcje zachowują się tak samo dla:
"""
answer.answer = "wszystkich danych wejściowych"
prompt.distractors = [ "żadnych danych wejściowych", "niektórych, ale nie wszystkich danych wejściowych" ]
context = """
`match` i `if` pełnią tu tę samą funkcję. `match` jest jak wyspecjalizowane `if`, które sprawdza równość dopasowywanego obiektu.
"""