[[questions]]
id = "904a0808-22d1-45e5-9611-cf143babbc41"
type = "MultipleChoice"
prompt.prompt = """
Która kolejność jest poprawna, jeśli „A > B” oznacza „A zawiera B”?
"""
answer.answer = "pakiet > crate > moduł"
prompt.distractors = [ "moduł > crate > pakiet", "crate > pakiet > moduł" ]
context = """
Pakiet to jednostka organizacyjna najwyższego poziomu, zawierająca crate’y. Crate zawiera moduły.
"""

[[questions]]
id = "d45c7cbe-6089-40b9-843c-fbb9ff48ca49"
type = "ShortAnswer"
prompt.prompt = """
Wyobraź sobie pakiet Rusta `foobar` z następującymi plikami:

```text
foobar
├── Cargo.toml
├── build.rs
└── src/
    ├── main.rs
    ├── util.rs
    ├── lib.rs
    └── bin/
        └── alt.rs
```

Ile crate’ów zawiera ten pakiet? Wpisz odpowiedź jako cyfrę, np. 0, 1 itd.
"""
answer.answer = "3"
context = """ 
Z `main.rs` powstaje crate binarny, z `lib.rs` – crate biblioteczny, a z `bin/alt.rs` – crate binarny. Plik `util.rs` byłby zapewne używany jako moduł w
jednym z tych crate’ów, ale jego nazwa nie jest specjalną nazwą rozpoznawaną przez Rusta, więc nie byłby osobnym crate’em. `build.rs` to skrypt budowania.
"""
