[[questions]]
id = "8ef2f170-71d9-4f17-a688-b99d8c8072a8"
type = "Tracing"
prompt.program = """
pub mod a {
  pub mod b {
    pub fn f() { println!("b1"); }
    pub mod c {
      pub fn f() { println!("c1"); }
    }
  }
  pub fn entry() { super::b::c::f(); }
}

pub mod b {
  pub fn f() { println!("b2"); }
  pub mod c {
    pub fn f() { println!("c2"); }
  }
}

fn main() {
  crate::a::entry();
}
"""
answer.doesCompile = true
answer.stdout = "c2"
context = """
`entry` używa ścieżki `super::b::c::f`. `entry` znajduje się w module `a`, więc `super` odnosi się do rodzica modułu `a`, czyli do korzenia crate’a. 
Dzieckiem korzenia o nazwie `b` jest najbardziej zewnętrzny moduł `b`, którego dziecko `c` zawiera funkcję `f` wypisującą `"c2"`.
"""

[[questions]]
id = "153b12b3-4fbc-449c-99a6-7a2cd469df0f"
type = "Tracing"
prompt.program = """
pub mod point {
  #[derive(Debug)]
  pub struct Point(i32, i32);

  impl Point {
    pub fn origin() -> Self { Point(0, 0) }
  }
}

fn main() {
  let mut p = point::Point::origin();
  p.0 += 1;
  println!("{p:?}");
}
"""
answer.doesCompile = false
answer.lineNumber = 12
context = """
Choć zarówno struktura `Point`, jak i metoda statyczna `origin` są publiczne, pole `i32` nie jest oznaczone jako pub. Dlatego bezpośredni dostęp do `p.0` poza
modułem `point` jest niedozwolony. Program skompilowałby się, gdyby zmienić wiersz 3 na `pub struct Point(pub i32, pub i32)`.
"""