[[questions]]
id = "6a94bc90-6cc5-4a47-838c-596d3747b7e4"
type = "ShortAnswer"
prompt.prompt = """
Wyobraź sobie pakiet Rusta o następującej strukturze katalogów:

```text
foobar
├── Cargo.toml
└── src/
    ├── lib.rs
    ├── engine.rs
    └── engine/
        └── analysis.rs
```

Zawartość poszczególnych plików jest taka:


```
// engine/analysis.rs
pub fn run() {}
```

```
// engine.rs
mod analysis;
pub use analysis::*;
```

```
// lib.rs
pub mod engine;
```

Załóżmy, że inny programista Rusta używa crate’a bibliotecznego `foobar` w osobnym pakiecie i chce wywołać funkcję `run`.
Jaką ścieżkę musiałby napisać?
"""
answer.answer = "foobar::engine::run"
answer.alternatives = ["foobar::engine::run()"]
context = """
Drzewo modułów wygenerowane na podstawie tej struktury katalogów wygląda tak:

```text
foobar
└── engine
    └── run  
```

Dlatego ścieżka do `run` to `foobar::engine::run`.
"""
