[[questions]]
id = "4e18f340-e336-43c5-9a95-79dec1f49945"
type = "ShortAnswer"
prompt.prompt = "Jakiego słowa kluczowego używa się na początku ścieżki bezwzględnej do elementu w bieżącym crate’cie?"
answer.answer = "crate"
context = """
Na przykład ścieżka bezwzględna do elementu `b` w module `a` to `crate::a::b`.
"""

[[questions]]
id = "256d0ce2-da89-4b44-94da-177634fc633a"
type = "Tracing"
prompt.program = """
pub mod foo {
  fn a() { println!("a"); }
  mod bar {
    pub fn b() { println!("b"); }
  }
}

fn main() {
  foo::bar::b();
}
"""
answer.doesCompile = false
answer.lineNumber = 9
context = """
Funkcja `b` jest niedostępna dla `main`, bo moduł `bar` nie jest oznaczony jako `pub`.
"""

[[questions]]
id = "5e78e2e4-81dc-42b2-8527-f08b5117982f"
type = "Tracing"
prompt.program = """
pub mod foo {
  pub mod bar {
    pub fn b() { println!("b");  }
  }
  pub fn a() { bar::b(); }
}

fn main() {
  foo::a();
}
"""
answer.doesCompile = true
answer.stdout = "b"
context = """
Wewnątrz `foo` można odwoływać się do elementów w `bar` za pomocą ścieżki względnej.
"""
