[[questions]]
id = "23c95879-aae2-4121-bf89-21278f7b6ec6"
type = "MultipleChoice"
prompt.prompt = """
Która z poniższych NIE jest zaletą używania modułów?
"""
answer.answer = "Moduły zwiększają wydajność w czasie działania wzajemnie zależnego kodu w obrębie tego samego modułu"
prompt.distractors = [
  "Moduły grupują powiązany kod, dzięki czemu programistom łatwiej pracować nad dużą bazą kodu",
  "Moduły hermetyzują szczegóły implementacji, których nie powinni używać klienci zewnętrzni",
  "Moduły zapewniają zasięg, który pozwala uniknąć konfliktów nazw między częściami bazy kodu"
]
context = """
Moduły nie mają wpływu na czas działania programu – służą wyłącznie do organizacji kodu w czasie kompilacji.
"""
