[[questions]]
id = "5af7c045-95dc-4bd0-9318-7204732e3ed5"
type = "Tracing"
prompt.program = """
fn main() {
  let mut v = vec![1, 2, 3];
  for i in &mut v {
    v.push(*i);
  }
  println!("{} {} {}", v[3], v[4], v[5]);
}
"""
answer.doesCompile = false
answer.lineNumber = 4
context = """
Choć `v` jest pożyczony mutowalnie, pozwala to wewnątrz pętli for modyfikować tylko `i`, a nie `v`. Dlatego wywołanie `v.push` jest błędem własności.
"""

[[questions]]
id = "e8da8773-8df2-4279-8c27-b7e9eda1dddd"
type = "Tracing"
prompt.program = """
fn main() {
  let mut v: Vec<i32> = vec![1, 2, 3];
  let mut v2: Vec<&mut i32> = Vec::new();
  for i in &mut v {
    v2.push(i);
  }
  *v2[0] = 5;

  let a = *v2[0];
  let b = v[0];
  println!("{a} {b}");
}
"""
answer.doesCompile = true
answer.stdout = "5 5"
context = """
`i` ma typ `&mut i32`, czyli jest wskaźnikiem na liczbę wewnątrz `v`. Jeśli więc dodamy `i` do `v2`, to `v2` zawiera wskaźniki do `v`. Dlatego
modyfikowanie `v2[0]` w rzeczywistości modyfikuje `v[0]`.
"""