[[questions]]
id = "da6daf92-5b2c-4f8d-97de-6905dbc77936"
type = "MultipleChoice"
prompt.prompt = "Które stwierdzenie najlepiej wyjaśnia, dlaczego Rust nie pozwala indeksować łańcuchów?"
answer.answer = "Indeksowanie łańcuchów jest niejednoznaczne, ponieważ łańcuchy reprezentują ciągi danych na kilku poziomach szczegółowości"
prompt.distractors = [
  "Indeksowanie łańcuchów jest niebezpieczne, ponieważ może spowodować błąd segmentacji lub przepełnienie bufora",
  "Indeksowanie łańcuchów jest niewydajne, ponieważ łańcuchy są zakończone znakiem null, więc nie da się wydajnie obliczyć ich długości",
  "Indeksowanie łańcuchów sprawiłoby, że Rust byłby zbyt łatwy w użyciu, a programiści Rusta potrzebują pewności zatrudnienia"
]
context = """
Łańcuch w UTF-8 można interpretować jako ciąg bajtów, znaków lub klastrów grafemów. Żaden z tych sposobów nie musi być „domyślnym”
sposobem interpretowania łańcucha, więc domyślna operacja indeksowania nie ma sensu.
"""

[[questions]]
id = "9366278e-a3f5-4759-ac72-e3c7d248da44"
type = "MultipleChoice"
prompt.prompt = """
Które stwierdzenie najlepiej opisuje różnicę między typami wycinka łańcucha `&str` i wycinka bajtów `&[u8]`?
"""
answer.answer = "`&str` wskazuje na bajty, które zawsze można zinterpretować jako UTF-8, a `&[u8]` może być dowolnym ciągiem bajtów"
prompt.distractors = [
  "`&str` zawsze wskazuje na dane przechowywane w pliku binarnym programu, a `&[u8]` może być przechowywany w dowolnym miejscu pamięci",
  "Z `&str` nie można utworzyć kolejnego wycinka, a z `&[u8]` można",
  "`&str` można utworzyć ze `String`, a `&[u8]` może pochodzić tylko z `Vec`"
]
context = """
`&str` to obietnica, że ciąg bajtów, na który wskazuje, zawsze będzie poprawnym UTF-8. Dlatego programista, który chce np. wypisać
`&str`, nigdy nie musi sprawdzać, czy jest on poprawny, ani martwić się przypadkowym zinterpretowaniem niepoprawnego łańcucha.
"""
