[[questions]]
id = "867e5d29-c1eb-44b3-99e3-bb2325b74e44"
type = "MultipleChoice"
prompt.prompt = """
**Program 1:**

```ide
/// Removes all the zeros in-place from a vector of integers.
fn remove_zeros(v: &mut Vec<i32>) {
    for (i, t) in v.iter().enumerate().rev() {
        if *t == 0 {
            v.remove(i);
            v.shrink_to_fit();
        }
    }
}
```

Które z poniższych najlepiej opisuje błąd, jaki zgłosiłby kompilator przy próbie skompilowania tej funkcji?
"""
answer.answer = "`v.remove(i)` nie może pożyczyć `v` jako mutowalnego"
prompt.distractors = [
  "`v` nie żyje wystarczająco długo, by wywołać `v.remove(i)`",
  "nie można wykonać dereferencji `t`, dopóki `i` żyje",
  "nie można wywołać `v.iter()` na referencji mutowalnej"
]
context = """
Funkcja `v.iter()` pożycza wektor `v` niemutowalnie na czas trwania pętli for. Jednak `v.remove(i)` wymaga mutowalnej
referencji do `v`. Dlatego `v.remove(i)` nie może pożyczyć `v` jako mutowalnego, bo kolidowałoby to z iteratorem.
"""


[[questions]]
id = "dd1bd092-ef8d-4293-a4d6-6a59b5887e98"
type = "MultipleChoice"
prompt.prompt = """
**Program 1:**

```ide
/// Removes all the zeros in-place from a vector of integers.
fn remove_zeros(v: &mut Vec<i32>) {
    for (i, t) in v.iter().enumerate().rev() {
        if *t == 0 {
            v.remove(i);
            v.shrink_to_fit();
        }
    }
}
```

Normalnie przy próbie skompilowania tej funkcji kompilator zwraca następujący błąd:

```text
error[E0502]: cannot borrow `*v` as mutable because it is also borrowed as immutable
 --> test.rs:5:13
  |
3 |     for (i, t) in v.iter().enumerate().rev() {
  |                   --------------------------
  |                   |
  |                   immutable borrow occurs here
  |                   immutable borrow later used here
4 |         if *t == 0 {
5 |             v.remove(i);
  |             ^^^^^^^^^^^ mutable borrow occurs here
```

Załóż, że kompilator NIE odrzucił tej funkcji. Które z poniższych programów (jeśli w ogóle jakieś)
(1) przeszłyby przez kompilator i (2) mogłyby spowodować niezdefiniowane zachowanie po wykonaniu?
Zaznacz każdy program, który spełnia oba kryteria, ALBO zaznacz „Żaden z tych programów”, jeśli żaden ich nie spełnia.
"""
answer.answer = [
"""
```
let mut v = vec![5, 5, 0];
remove_zeros(&mut v);
println!("{:?}", v);
```
""",
"""
```
let mut v = vec![1, 2, 0, 3];
remove_zeros(&mut v);
```
""", 
]
prompt.distractors = [
"""
```
let mut v = vec![1; 100];
remove_zeros(&mut v);
```
""",
"Żaden z tych programów",
]
context = """
Aby naruszyć bezpieczeństwo pamięci, `remove_zeros` musi zostać wywołane z wektorem zawierającym zero po pierwszym elemencie.
Wywołanie `v.shrink_to_fit()` zdealokuje pamięć, której właścicielem jest wektor (z powodu zmiany rozmiaru), co unieważni
iterator `v.iter()` zawierający wskaźnik na stare dane. Zauważ, że odczyt wektora `v` po wywołaniu `remove_zeros`
nie jest niezbędny do naruszenia bezpieczeństwa, ponieważ problem występuje wewnątrz `remove_zeros`.
"""

[[questions]]
id = "c7e7e1e1-2788-4dd9-9c18-436bc95b405f"
type = "MultipleChoice"
prompt.prompt = """
**Program 1:**

```ide
/// Removes all the zeros in-place from a vector of integers.
fn remove_zeros(v: &mut Vec<i32>) {
    for (i, t) in v.iter().enumerate().rev() {
        if *t == 0 {
            v.remove(i);
            v.shrink_to_fit();
        }
    }
}
```

Która z poniższych poprawek (wyróżnionych na żółto) najlepiej spełnia te trzy kryteria:
1. Poprawiona funkcja przechodzi przez kompilator Rusta;
2. Poprawiona funkcja zachowuje intencję oryginalnego kodu;
3. Poprawiona funkcja nie wprowadza zbędnej nieefektywności.
"""
answer.answer = """
```ide
fn remove_zeros(v: &mut Vec<i32>) {
    for `[i in (0 .. v.len()).rev()]` {
        if `[v[i]]` == 0 {
            v.remove(i);
            v.shrink_to_fit();
        }
    }
}
```
"""
prompt.distractors = [
"""
```ide
fn remove_zeros(v: &mut Vec<i32>) {
    for (i, t) in v`[.clone()]`.iter().enumerate().rev() {
        if *t == 0 {
            v.remove(i);
            v.shrink_to_fit();
        }
    }
}
```
""",
"""
```ide
fn remove_zeros(v: `[&]`Vec<i32>) `[-> Vec<i32>]` {
    `[let mut new_vec = Vec::new();]`
    for (i, t) in v.iter().enumerate().rev() {
        if *t `[!=]` 0 {
            `[new_vec.push(*t)]`
        }
    }
    `[new_vec]`
}
```
""",
"""
```ide
fn remove_zeros(v: `[Vec<i32>]`) {
    for (i, t) in v.iter().enumerate().rev() {
        if *t == 0 {
            v.remove(i);
            v.shrink_to_fit();
        }
    }
}
```
""",
]
context = """
Każda strategia wymagająca utworzenia nowego wektora, czy to przez `Vec::clone`, czy przez `Vec::new`, wymaga zbędnej dodatkowej alokacji.
Dlatego najprostszą działającą strategią jest iterowanie wyłącznie po indeksach `0 .. v.len()`, co nie pożycza `v`. Robimy to
w odwrotnej kolejności, aby nie usuwać nieistniejących indeksów.

Podobnie jak w problemie 1, najbardziej idiomatyczną strategią jest w rzeczywistości użycie wbudowanej funkcji, której jeszcze nie omawialiśmy:
[`Vec::retain`](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.retain). Ta funkcja zachowuje w wektorze tylko elementy
spełniające predykat, ale robi to oszczędniej pod względem pamięci.
"""

[[questions]]
id = "fb0e3080-7cc8-4338-948e-fae693d137c8"
type = "MultipleChoice"
prompt.prompt = """
**Program 2:**

```ide
/// Reverses the elements of a vector in-place
fn reverse(v: &mut Vec<String>) {
    let n = v.len();
    for i in 0 .. n / 2 {
        std::mem::swap(&mut v[i], &mut v[n - i - 1]);
    }
}
```

Które z poniższych najlepiej opisuje błąd, jaki zgłosiłby kompilator przy próbie skompilowania tego programu?
"""
answer.answer = "nie można pożyczyć `v` jako mutowalnego dwukrotnie dla `v[i]` i `v[n - i - 1]`"
prompt.distractors = [
  "nie można pożyczyć `v` jako niemutowalnego dla `v.len()`, gdy `v` jest pożyczeniem mutowalnym",
  "nie można mutowalnie pożyczyć elementu `v[i]` mutowalnego wektora"
]
context = """
Kompilator nie bierze pod uwagę konkretnych wartości indeksów używanych do dostępu do tablicy, więc zakłada, że `&mut v[i]`
i `&mut v[n - i - 1]` mogą wskazywać na ten sam element. Dlatego dostajemy błąd mówiący, że
`v` nie może zostać dwukrotnie pożyczony mutowalnie.
"""


[[questions]]
id = "4c703871-3cc3-483f-beb5-876bdbcd223b"
type = "MultipleChoice"
prompt.prompt = """
**Program 2:**

```ide
/// Reverses the elements of a vector in-place
fn reverse(v: &mut Vec<String>) {
    let n = v.len();
    for i in 0 .. n / 2 {
        std::mem::swap(&mut v[i], &mut v[n - i - 1]);
    }
}
```

Normalnie przy próbie skompilowania tej funkcji kompilator zwraca następujący błąd:

```text
error[E0499]: cannot borrow `*v` as mutable more than once at a time
 --> test.rs:5:40
  |
5 |         std::mem::swap(&mut v[i], &mut v[n - i - 1]);
  |         --------------      -          ^ second mutable borrow occurs here
  |         |                   |
  |         |                   first mutable borrow occurs here
  |         first borrow later used by call
```

Załóż, że kompilator NIE odrzucił tej funkcji. Które z poniższych programów (jeśli w ogóle jakieś)
(1) przeszłyby przez kompilator i (2) mogłyby spowodować niezdefiniowane zachowanie po wykonaniu?
Zaznacz każdy program, który spełnia oba kryteria, ALBO zaznacz „Żaden z tych programów”, jeśli żaden ich nie spełnia.
"""
answer.answer = ["Żaden z tych programów"]
prompt.distractors = [
"""
```
let mut v = vec![String::from("a"), String::from("b")];
let x = &v[0];
reverse(&mut v);
println!("{x}");
```
""",
"""
```
let mut v = vec![String::from("a"), String::from("b")];
reverse(&mut v);
```
""",
"""
```
let mut v = vec![String::from("a"), String::from("b")];
reverse(&mut v);
println!("{:?}", v);
```
""",
]
context = """
Ta funkcja nie może naruszyć bezpieczeństwa pamięci, ponieważ `i != n - i - 1` dla każdego `i`, więc dwie
mutowalne referencje zawsze wskazują na różne elementy. Zauważ, że program z `let x = &v[0]` by się nie
skompilował, ponieważ borrow checker Rusta nie pozwoliłby wywołać `reverse`, dopóki `x` żyje.
"""

[[questions]]
id = "380fc77f-190d-4386-9e0e-f9360bbbfd98"
type = "MultipleChoice"
prompt.prompt = """
**Program 2:**

```ide
/// Reverses the elements of a vector in-place
fn reverse(v: &mut Vec<String>) {
    let n = v.len();
    for i in 0 .. n / 2 {
        std::mem::swap(&mut v[i], &mut v[n - i - 1]);
    }
}
```

Która z poniższych poprawek (wyróżnionych na żółto) najlepiej spełnia te trzy kryteria:
1. Poprawiona funkcja przechodzi przez kompilator Rusta;
2. Poprawiona funkcja zachowuje intencję oryginalnego kodu;
3. Poprawiona funkcja nie wprowadza zbędnej nieefektywności.
"""
answer.answer = """
```ide
fn reverse(v: &mut Vec<String>) {
    let n = v.len();
    for i in 0 .. n / 2 {
        `[let p1 = &mut v[i] as *mut String;]`
        `[let p2 = &mut v[n - i - 1] as *mut String;]`
        `[unsafe { std::ptr::swap_nonoverlapping(p1, p2, 1); }]`
    }
}
```
"""
prompt.distractors = [
"""
```ide
fn reverse(v: &mut Vec<String>) {
    let n = v.len();
    `[let mut v2 = v.clone();]`
    for i in 0 .. n / 2 {
        std::mem::swap(&mut v[i], &mut `[v2]`[n - i - 1]);
    }
}
```
""",
"""
```ide
fn reverse(v: `[&Vec<String>]`) -> `[Vec<String>]` {
    let n = v.len();
    `[let mut v2 = Vec::new();]`    
    for _ in 0 .. `[n]` {
        `[v2.push(v.pop().unwrap());]`
    }
    `[v2]`
}
```
""",
"""
```ide
fn reverse(v: &mut Vec<String>) {
    let n = v.len();    
    for i in 0 .. n / 2 {
        `[let s1 = v[i].clone();]`
        `[let s2 = v[n - i - 1].clone();]`
        `[v[i] = s2;]`
        `[v[n - i - 1] = s1;]`
    }
}
```
""",
]
context = """
Gdy borrow checker odrzuca operację, która w rzeczywistości jest bezpieczna i nie da się jej obejść,
niebezpieczny kod bywa dopuszczalny, jeśli uniknięcie alokacji ma kluczowe znaczenie.
W tym konkretnym przypadku należy jednak użyć [`Vec::swap`](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.swap), która wewnętrznie jest zaimplementowana
za pomocą gruntownie przetestowanego kodu `unsafe`, podobnego do powyższego.
Ogólnie jednak, jeśli biblioteka standardowa akurat nie obsługuje twojego przypadku użycia, `unsafe` może być dopuszczalne, o ile jest używane poprawnie.
"""