[[questions]]
id = "18bf21e1-4e1a-4e98-861d-c7032710a8ad"
type = "ShortAnswer"
prompt.prompt = "Jak nazywa się zmienna środowiskowa, którą należy ustawić na `1`, aby zobaczyć ślad stosu paniki?"
answer.answer = "RUST_BACKTRACE"
context = """
Na przykład możesz uruchomić w wierszu poleceń: `RUST_BACKTRACE=1 cargo run`
"""

[[questions]]
id = "23cabd75-88f5-4ff8-8bf5-4bd4d1a9e64a"
type = "MultipleChoice"
prompt.prompt = "Co z poniższych NIE jest dobrym powodem do użycia paniki?"
answer.answer = "Program znalazł się w stanie błędu, o którym należy poinformować funkcję wywołującą"
prompt.distractors = [
  "Program ma za chwilę wykonać niebezpieczną operację",
  "Program powinien jak najszybciej przerwać wykonywanie",
  "Program znalazł się w nieodwracalnym stanie błędu"
]
context = """
Paniki nie należy używać do sygnalizowania niepowodzenia *wewnątrz* programu. Domyślnie zakłada się, że funkcje
wywołujące nie będą próbowały przechwytywać paniki.
"""
