[[questions]]
id = "91fb1ec6-fb11-4b6f-88df-dbc921a4108f"
type = "MultipleChoice"
prompt.prompt = "Dane jest dowolne wyrażenie `e` typu `Result<T, E>`. Który fragment kodu najlepiej oddaje, na co tłumaczone jest `e?`?"
answer.answer = """
```
match e {
  Ok(x) => x,
  Err(err) => { return Err(err); }
}
```
  """
prompt.distractors = [
  """
```
if let Err(err) = e {
  return Err(err);
}
```
  """,
  """
```
e.unwrap()
```
  """,
  """
```
match e {
  Ok(x) => x,
  Err(err) => panic!("{err}")
}
```
  """,
]
context = """
Jeśli `e` jest typu `Result`, to `e?` wydobywa wartość z wnętrza `Ok`, jeśli to możliwe, a w przeciwnym razie zwraca `Err` z bieżącej funkcji.
"""

[[questions]]
id = "0ea46358-f560-4d3e-85d2-a1806eb7c797"
type = "Tracing"
prompt.program = """
// assume hello.txt has the contents "will"

fn read_username_from_file() -> Option<String> {
  let mut username_file = File::open("hello.txt")?;
  let mut username = String::new();
  username_file.read_to_string(&mut username)?;
  Some(username)
}

fn main() {
  println!("{}", read_username_from_file().unwrap()); 
}
"""
answer.doesCompile = false
answer.lineNumber = 4
context = """
`File::open` zwraca `Result`, ale typem zwracanym `read_username_from_file` jest `Option`. Dlatego nie można użyć operatora `?`,
dopóki `Result` nie zostanie przekonwertowany na `Option` (np. metodą `Result::ok`).
"""