[[questions]]
id = "8f9e0e79-f4a7-4056-b35e-f7ae65b78888"
type = "MultipleChoice"
prompt.prompt = "Które z tych stwierdzeń najlepiej wyjaśnia, dlaczego `File::open` zwraca `Result`, a nie `Option`?"
answer.answer = "Ponieważ `Result` może wyrazić, dlaczego operacja się nie powiodła, a otwarcie pliku może się nie udać z wielu powodów"
prompt.distractors = [
  "Ponieważ `Result` reprezentuje możliwość niepowodzenia, a `Option` nie może reprezentować niepowodzeń",
  "Ponieważ `Result` w czasie działania zużywa mniej bajtów niż `Option` do reprezentowania niepowodzeń",
  "Ponieważ `Result` reprezentuje błędy tak samo jak leżące u podstaw wywołania systemowe"
]
context = """
`Option` może jedynie wyrazić, *że* operacja się nie powiodła, natomiast `Result` może wyjaśnić, *dlaczego* się nie powiodła.
"""