[[questions]]
id = "31c55174-3fdf-4a21-959c-bb4056def264"
type = "MultipleChoice"
prompt.prompt = """
Programista Rusta projektuje bibliotekę do tworzenia interfejsów wiersza poleceń.
W ramach tej biblioteki implementuje funkcję parsującą flagi wiersza poleceń podane przez użytkownika.
Która implementacja byłaby najwłaściwsza w tej dziedzinie?

```
fn parse_flag_v1(flag: &str) -> Result<String, String> {
  match flag.strip_prefix("--") {
    Some(no_dash) => Ok(no_dash.to_string()),
    None => Err(format!("Invalid flag {flag}"))
  }
}

fn parse_flag_v2(flag: &str) -> String {
  match flag.strip_prefix("--") {
    Some(no_dash) => no_dash.to_string(),
    None => panic!("Invalid flag {flag}")
  }
}
```
"""
answer.answer = "`parse_flag_v1`"
prompt.distractors = [ "`parse_flag_v2`" ]
prompt.answerIndex = 0
context = """
W tej sytuacji programista najpewniej chciałby użyć błędu *odwracalnego* (`Result`). Jeśli użytkownik CLI przekaże niepoprawnie sformatowaną flagę,
biblioteka CLI może chcieć udzielić dodatkowej pomocy, np. wyświetlić zestaw dostępnych flag. Panika zmusiłaby aplikację
do pokazania wyłącznie komunikatu paniki i prawdopodobnie byłaby gorszym doświadczeniem dla użytkownika.
"""
