[[questions]]
id = "9ff33b87-38e2-471b-8ca4-9c31a6431376"
type = "MultipleChoice"
prompt.prompt = """
**Program 1:**

```ide
/// Returns the n-th largest element in a slice
fn find_nth<T: Ord + Clone>(elems: &[T], n: usize) -> T {
    elems.sort();
    let t = &elems[n];
    return t.clone();
}
```

Które z poniższych najlepiej opisuje błąd, jaki zgłosiłby kompilator przy próbie skompilowania tego programu?
"""
answer.answer = "nie można pożyczyć `elems` jako mutowalnego dla `sort`"
prompt.distractors = [
  "nie można przenieść wartości spod referencji współdzielonej dla `clone`",
  "nie można przenieść wartości spod referencji współdzielonej w wyrażeniu `&elems[n]`",
  "czas życia `T` musi być dłuższy niż czas życia `&[T]`",
]
context = """
Metoda `slice::sort` oczekuje mutowalnej referencji do wycinka, ale
zamiast niej dostaje referencję niemutowalną.
"""


[[questions]]
id = "3ee8d846-d282-4de1-8e83-5ca0bc44fc13"
type = "MultipleChoice"
prompt.prompt = """
**Program 1:**

```ide
/// Returns the n-th largest element in a slice
fn find_nth<T: Ord + Clone>(elems: &[T], n: usize) -> T {
    elems.sort();
    let t = &elems[n];
    return t.clone();
}
```

Normalnie przy próbie skompilowania tej funkcji kompilator zwraca następujący błąd:

```text
error[E0596]: cannot borrow `*elems` as mutable, as it is behind a `&` reference
 --> test.rs:3:5
  |
3 |     elems.sort();
  |     ^^^^^^^^^^^^ `elems` is a `&` reference, so the data it refers to cannot be borrowed as mutable
```

Załóż, że kompilator NIE odrzucił tej funkcji. Które z poniższych programów (jeśli w ogóle jakieś)
(1) przeszłyby przez kompilator i (2) mogłyby spowodować niezdefiniowane zachowanie po wykonaniu?
Zaznacz każdy program, który spełnia oba kryteria, ALBO zaznacz „Żaden z tych programów”, jeśli żaden ich nie spełnia.
"""
answer.answer = ["Żaden z tych programów"]
prompt.distractors = [
"""
```
let v = vec![5, 4, 3, 2, 1];
find_nth(&v, 10);
```
""",
"""
```
let v = vec![5, 4, 3, 2, 1];
find_nth(&v, 0);
println!("{}", v[0]);
```
""",
"""
```
let v = vec![5, 4, 3, 2, 1];
let n = &v[0];
find_nth(&v, 0);
println!("{}", n);
```
""",
]
context = """
Ten program jest formalnie bezpieczny pod względem pamięci, ponieważ `slice::sort` potrafi jedynie przestawiać
elementy, a nie je zwalniać. Na przykład `&v[0]` po wywołaniu `find_nth` na pewno wskazuje na
*jakąś* liczbę, nawet jeśli nie jest to liczba *oryginalna*.

Zauważ, że `find_nth(&v, 10)` nie powoduje niezdefiniowanego zachowania, ponieważ Rust sprawdza
dostęp do elementów tablicy, więc obliczenie `&v[10]` spowoduje panikę.
"""


[[questions]]
id = "d070eb9e-4527-453a-8c9b-698739a3dd6a"
type = "MultipleChoice"
prompt.prompt = """
**Program 1:**

```ide
/// Returns the n-th largest element in a slice
fn find_nth<T: Ord + Clone>(elems: &[T], n: usize) -> T {
    elems.sort();
    let t = &elems[n];
    return t.clone();
}
```

Która z poniższych poprawek (wyróżnionych na żółto) najlepiej spełnia te trzy kryteria:
1. Poprawiona funkcja przechodzi przez kompilator Rusta;
2. Poprawiona funkcja zachowuje intencję oryginalnego kodu;
3. Poprawiona funkcja nie wprowadza zbędnej nieefektywności.
"""
answer.answer = """
```ide
fn find_nth<T: Ord + Clone>(elems: &[T], n: usize) -> T {
    `[let mut elem_refs: Vec<&T> = elems.iter().collect();]`
    `[elem_refs.sort();]`
    let t = `[elem_refs[n]]`;
    return t.clone();
}
```
"""
prompt.distractors = [
"""
```ide
fn find_nth<T: Ord + Clone>(`[elems: &mut [T]]`, n: usize) -> T {
    elems.sort();
    let t = &elems[n];
    return t.clone();
}
```
""",
"""
```ide
fn find_nth<T: Ord + Clone>(elems: &[T], n: usize) -> T {
    `[let mut elems = elems.to_vec();]`
    elems.sort();
    let t = &elems[n];
    return t.clone();
}
```
""",
"""
```ide
fn find_nth<`[T: Ord]`>(`[mut elems: Vec<T>]`, n: usize) -> T {
    elems.sort();
    let t = `[elems.remove(n)]`;
    return `[t]`;
}
```
""",
]
context = """
Funkcja taka jak `find_nth` w oczywisty sposób ma jedynie odczytywać dane, tj.
wyznaczać pewną właściwość sekwencji wejściowej. Dlatego żadne rozwiązanie, które modyfikuje lub zwalnia dane wejściowe, nie zachowuje intencji oryginalnej funkcji, nawet jeśli
jest wydajniejsze niż tworzenie pomocniczego wektora.

Utworzenie `Vec<&T>` jest lepsze niż utworzenie `Vec<T>`, ponieważ jeśli typ `T` jest duży, to
`elems.to_vec()` może być kosztowne. Gdybyśmy jednak wiedzieli, że `T: Copy`, to lepsze byłoby `to_vec`,
bo zmniejszyłoby liczbę dereferencji wskaźników w `elems.sort()`.
"""

[[questions]]
id = "95979d75-5823-4059-a1cf-7e0eba69b41a"
type = "MultipleChoice"
prompt.prompt = """
**Program 2:**

```ide
struct TestResult {
    /// Student's scores on a test
    scores: Vec<usize>,

    /// A possible value to curve all scores
    curve: Option<usize>
}
impl TestResult {  
    pub fn get_curve(&self) -> &Option<usize> { 
        &self.curve 
    }

    /// If there is a curve, then increments all 
    /// scores by the curve
    pub fn apply_curve(&mut self) {
        if let Some(curve) = self.get_curve() {
            for score in self.scores.iter_mut() {
                *score += *curve;
            }
        }
    }
}
```

Które z poniższych najlepiej opisuje błąd, jaki zgłosiłby kompilator przy próbie skompilowania tego programu?
"""
answer.answer = "w `apply_curve` nie można pożyczyć `self.scores` jako mutowalnego dla `iter_mut`"
prompt.distractors = [
  "w `get_curve` nie można zwrócić referencji do zmiennej lokalnej `self.curve`",
  "w `apply_curve` nie można pożyczyć `self` jako niemutowalnego dla `get_curve`",
  "w `apply_curve` nie można modyfikować `*score`"
]
context = """
Ze względu na pomijanie czasów życia funkcja `get_curve` ma sygnaturę typu `get_curve<'a>(&'a self) -> &'a Option<usize>`.
Oznacza to, że wywołanie `self.get_curve()` przedłuża pożyczenie całego `self`, a nie tylko `self.curve`.
Dlatego `self` jest niemutowalnie pożyczone w zasięgu `let Some(curve) = ...` i nie można wywołać
`self.scores.iter_mut()`.
"""


[[questions]]
id = "dcb42a15-d9b7-437d-95ec-f000b64ce277"
type = "MultipleChoice"
prompt.prompt = """
**Program 2:**

```ide
struct TestResult {
    /// Student's scores on a test
    scores: Vec<usize>,

    /// A possible value to curve all scores
    curve: Option<usize>
}
impl TestResult {  
    pub fn get_curve(&self) -> &Option<usize> { 
        &self.curve 
    }

    /// If there is a curve, then increments all 
    /// scores by the curve
    pub fn apply_curve(&mut self) {
        if let Some(curve) = self.get_curve() {
            for score in self.scores.iter_mut() {
                *score += *curve;
            }
        }
    }
}
```

Normalnie przy próbie skompilowania tej funkcji kompilator zwraca następujący błąd:

```text
error[E0502]: cannot borrow `self.scores` as mutable because it is also borrowed as immutable
  --> test.rs:17:26
   |
16 |         if let Some(curve) = self.get_curve() {
   |                              ---------------- immutable borrow occurs here
17 |             for score in self.scores.iter_mut() {
   |                          ^^^^^^^^^^^^^^^^^^^^^^ mutable borrow occurs here
18 |                 *score += *curve;
   |                           ------ immutable borrow later used here
```

Załóż, że kompilator NIE odrzucił tej funkcji. Które z poniższych programów (jeśli w ogóle jakieś)
(1) przeszłyby przez kompilator i (2) mogłyby spowodować niezdefiniowane zachowanie po wykonaniu?
Zaznacz każdy program, który spełnia oba kryteria, ALBO zaznacz „Żaden z tych programów”, jeśli żaden ich nie spełnia.
"""
answer.answer = ["Żaden z tych programów"]
prompt.distractors = [
"""
```
let mut result = TestResult { 
    scores: vec![20, 50, 30], 
    curve: Some(10) 
};
result.apply_curve();
```
""",
"""
```
let mut result = TestResult { 
    scores: vec![20, 50, 30], 
    curve: Some(10) 
};
let x = &result.scores[0];
result.apply_curve();
println!("{}", x);
```
""",
"""
```
let mut result = TestResult { 
    scores: vec![20, 50, 30], 
    curve: Some(10) 
};
result.apply_curve();
println!("{:?}", result.scores);
```
""",
]
context = """
Ten program w obecnej postaci jest w rzeczywistości bezpieczny. Borrow checker ma tu ograniczenie: nie rozumie, że `get_curve`
pożycza tylko `curve` i nie wpływa na `scores`. Teoretycznie jednak, gdyby `get_curve` zmieniono tak, aby zwracała referencję
do czegoś w `self.scores`, bezpieczeństwo pamięci mogłoby zostać naruszone.
"""

[[questions]]
id = "aa93c497-9864-4799-b69b-7de42c158f2a"
type = "MultipleChoice"
prompt.prompt = """
**Program 2:**

```ide
struct TestResult {
    /// Student's scores on a test
    scores: Vec<usize>,

    /// A possible value to curve all scores
    curve: Option<usize>
}
impl TestResult {  
    pub fn get_curve(&self) -> &Option<usize> { 
        &self.curve 
    }

    /// If there is a curve, then increments all 
    /// scores by the curve
    pub fn apply_curve(&mut self) {
        if let Some(curve) = self.get_curve() {
            for score in self.scores.iter_mut() {
                *score += *curve;
            }
        }
    }
}
```

Która z poniższych poprawek (wyróżnionych na żółto) najlepiej spełnia te trzy kryteria:
1. Poprawiona funkcja przechodzi przez kompilator Rusta;
2. Poprawiona funkcja zachowuje intencję oryginalnego kodu;
3. Poprawiona funkcja nie wprowadza zbędnej nieefektywności.
"""
answer.answer = """
```ide
pub fn apply_curve(&mut self) {
    if let Some(curve) = `[self.curve]` {
        for score in self.scores.iter_mut() {
            *score += curve;
        }
    }
}
```
"""
prompt.distractors = [
"""
```ide
pub fn apply_curve(&mut self) {
    if let Some(curve) = self.get_curve()`[.as_ref()]` {
        for score in self.scores.iter_mut() {
            *score += *curve;
        }
    }
}
```
""",
"""
```ide
pub fn apply_curve(&mut self) {
    if let Some(curve) = self.get_curve() {
        for score in self.scores`[.clone()]`.iter_mut() {
            *score += *curve;
        }
    }
}
```
""",
"""
```ide
pub fn apply_curve(&mut self) {
    if let Some(curve) = self.get_curve() {
        for score in self.scores`[.iter()]` {
            *score += *curve;
        }
    }
}
```
""",
]
context = """
Po wstawieniu definicji `get_curve` bezpośrednio do `apply_curve` borrow checker rozumie, że `self.curve` to nie `self.scores`,
więc pozwala skompilować funkcję. To częsty sposób obejścia tego rodzaju ograniczeń borrow checkera.

Inną możliwością jest wykorzystanie faktu, że `self.curve` można tanio skopiować, i użycie [`Option::copied`](https://doc.rust-lang.org/std/option/enum.Option.html#method.copied),
co zakończyłoby pożyczenie `self` zaraz po wywołaniu `.copied()`.
"""