[[questions]]
id = "c4adb1a8-ca6a-43c1-ae34-54302f674ece"
type = "Tracing"
prompt.program = """
trait MakeNoise {
  fn make_noise(&self) {
    println!("(silence)");
  }
}

struct Dog {}
struct Cat {}

impl MakeNoise for Dog {
  fn make_noise(&self) {
    println!("bark");
  }
}

impl MakeNoise for Cat {}

fn main() {
  let dog = Dog {};
  let cat = Cat {};
  dog.make_noise();
  cat.make_noise();
}
"""
answer.doesCompile = true
answer.stdout = "bark\n(silence)"
context = """
Implementacja `MakeNoise` zapewnia konkretną implementację dla `Dog` i używa implementacji domyślnej dla `Cat`.
Dlatego wywołanie `make_noise` na każdym z nich wypisuje odpowiednio `bark` i `(silence)`.
"""

[[questions]]
id = "783f2485-e5b9-483b-8368-064366c77285"
type = "MultipleChoice"
prompt.prompt = "Poniżej znajdują się stwierdzenia o tym, jakie implementacje traitów dopuszcza Rust. Zaznacz każde prawdziwe stwierdzenie."
prompt.distractors = ["Można zaimplementować zewnętrzny trait dla zewnętrznego typu"]
answer.answer = [
  "Można zaimplementować zewnętrzny trait dla lokalnego typu",
  "Można zaimplementować lokalny trait dla zewnętrznego typu",
  "Można zaimplementować lokalny trait dla lokalnego typu"
]
context = """
„Reguła sieroty” zabrania implementowania zewnętrznego traitu dla zewnętrznego typu,
aby kod nie przestał działać, gdy dwa crate’y dostarczą sprzecznych implementacji.
"""