[[questions]]
id = "0aad53ff-89d7-4d14-8e3d-c17809220252"
type = "ShortAnswer"
prompt.prompt = """
Wyobraź sobie, że używasz funkcji z zewnętrznej biblioteki, której implementacji nie znasz, ale jej sygnatura typu wygląda tak:

```
fn mystery<T>(x: T) -> T {
  // ????
}
```

Następnie wywołujesz `mystery` w ten sposób:

```
let y = mystery(3);
```

Zakładając, że `mystery` nie używa niebezpiecznego kodu, wartość `y` musi wynosić:
"""
answer.answer = "3"
context = """
Jedyna możliwa funkcja (bez niebezpiecznego kodu) o sygnaturze `T -> T` to funkcja tożsamościowa:

```
fn mystery<T>(x: T) -> T {
  x
}
```

Funkcja mogłaby oczywiście spanikować albo coś wypisać, ale wartością zwracaną może być tylko jej argument. `mystery` nie wie,
jakim typem jest `T`, więc `mystery` nie ma jak wygenerować ani zmodyfikować wartości typu `T`.
Więcej przykładów tej idei znajdziesz w artykule [Theorems for free!](https://dl.acm.org/doi/pdf/10.1145/99370.99404).

**3 to naprawdę poprawna odpowiedź! Jeśli się z nią nie zgadzasz, prosimy, nie zgłaszaj błędu!**
"""

[[questions]]
id = "40ae0cfe-3567-4d05-b0d9-54d612a2d654"
type = "Tracing"
prompt.program = """
fn print_slice<T>(v: &[T]) {
  for x in v {
    println!("{x}");
  }
}

fn main() {
  print_slice(&[1, 2, 3]);
}
"""
answer.doesCompile = false
answer.lineNumber = 3
context = """
Jeśli typ jest generyczny (jak `T`), nie możemy niczego o nim zakładać, w tym tego, że da się go zamienić na łańcuch znaków. Dlatego `println!("{x}")` jest niepoprawne,
ponieważ `x: &T`.
"""


[[questions]]
id = "694bb2d0-f2e6-4b0b-a3e7-2d9f9e8b3d09"
type = "Tracing"
prompt.program = """
struct Point<T> { x: T, y: T }

impl Point<i32> {
  fn f(&self) -> &i32 { &self.y }
}

impl<T> Point<T> {
  fn f(&self) -> &T { &self.x }
}

fn main() {
  let p: Point<i32> = Point { x: 1, y: 2 };
  println!("{}", p.f());
}
"""
answer.doesCompile = false
answer.lineNumber = 8
context = """
Te definicje `f` są ze sobą sprzeczne i Rust nie jest w stanie ustalić, którego `f` użyć przy wywołaniu `p.f()`. Dlatego jest to błąd kompilacji.
"""
