[[questions]]
id = "8b7f93c3-efb0-44e2-a0ca-b45e35620b30"
type = "MultipleChoice"
prompt.prompt = "Jakiemu rodzajowi błędów programistycznych ma zapobiegać czas życia?"
answer.answer = "Użyciu referencji do obiektu po zwolnieniu jego pamięci"
prompt.distractors = [
  "Użyciu wyniku obliczenia, które może się nie powieść, przed sprawdzeniem, czy nie wystąpił błąd",
  "Indeksowaniu poza granicami tablicy (przepełnieniu bufora)",
  "Zaalokowaniu zbyt małej ilości pamięci dla obiektu"
]
context = """
Czasy życia pomagają ustalić, jak długo obiekt „żyje” i czy referencje do tego obiektu nie żyją dłużej niż sam obiekt. 
"""

[[questions]]
id = "77cf924a-ece1-4119-a762-f5f03536b4e1"
type = "Tracing"
prompt.program = """
fn shortest<'a, 'b>(x: &'a str, y: &'b str) -> &'a str {
  if x.len() < y.len() {
    x
  } else {
    y
  }
}

fn main() {
  println!("{}", shortest("hello", "rust"));
}
"""
answer.doesCompile = false
answer.lineNumber = 5
context = """
Jeśli sygnatura typu mówi, że funkcja musi zwrócić referencję o czasie życia `'a`, to zwrócenie
referencji o innym czasie życia '`b`, czyli tutaj `y`, byłoby niepoprawne.
"""
