[[questions]]
id = "a2a1546b-27bf-47d2-a1bc-86d777573f40"
type = "Tracing"
prompt.program = """
use std::fmt::Display;
fn displayable<T: Display>(t: T) -> impl Display { t }

fn main() {
  let s = String::from("hello");
  let mut s2 = displayable(s);
  s2.push_str(" world");
  println!("{s2}");
}
"""
answer.doesCompile = false
answer.lineNumber = 7
context = """
Ponieważ `displayable` zwraca `impl Display`, wiemy tylko, że `s2` jest *jakimś* typem implementującym `Display`,
a nie że jest typem `String`, który ma metodę `push_str`. Dlatego nie możemy wywołać `s2.push_str(..)`. Gdyby typ
zwracany przez `displayable` był określony jako `-> T`, ten program by się skompilował.
"""


[[questions]]
id = "8b35f91c-ced2-4b8f-bf1c-90550f2b744b"
type = "MultipleChoice"
prompt.prompt = """
Jaki jest najmniejszy zbiór ograniczeń traitów dla `T` potrzebny, aby ta funkcja przeszła sprawdzanie typów?
```
fn f<T: /* ??? */>(t: &T) {
  let t2 = t.clone();
  println!("{t2}");
}
```
"""
answer.answer = "`Clone + Display`"
prompt.distractors = [ "(brak ograniczeń)", "`Clone`", "`Clone + Display + Debug`" ]
context = """
Ponieważ wywoływana jest metoda `clone`, a w łańcuchu formatującym użyto nawiasów wyświetlania `{}`, `T` musi implementować `Clone` i `Display`.
"""
