[[questions]]
id = "a91417cd-cd6d-416b-b72d-4af6b3fb2fd6"
type = "MultipleChoice"
prompt.prompt = """
Jeśli referencja ma czas życia `'static`, oznacza to, że:
"""
answer.answer = "Dane wskazywane przez referencję nigdy nie są dealokowane"
prompt.distractors = [
  "Danych wskazywanych przez referencję nie można modyfikować",
  "Dane wskazywane przez referencję znajdują się w statycznym obszarze pamięci",
  "Dane wskazywane przez referencję nie są dynamiczne"
]
context = """
`'static` oznacza „żyje przez cały czas działania programu”, więc dane wskazywane przez statyczną referencję nigdy nie mogą zostać dealokowane. Choć w praktyce referencje `'static`
zwykle nie są mutowalne, znaczenie czasu życia `'static` nie ma zasadniczego związku z mutowalnością.
"""

[[questions]]
id = "e521409a-6cbd-48f5-bee0-7fa7f17cc562"
type = "MultipleChoice"
prompt.prompt = """
Rozważ następującą sygnaturę funkcji bez adnotacji.

```
struct Foo<'a> {
  bar: &'a i32
}

fn baz(f: Foo) -> &i32 { /* ... */ }
```

Czy Rust zaakceptuje tę sygnaturę funkcji? Jeśli tak, jakie czasy życia wywnioskuje?
"""
answer.answer = """
```
fn baz<'a>(f: Foo<'a>) -> &'a i32
```
  """
prompt.distractors = [
  "Rust odrzuci tę sygnaturę funkcji",
  """
```
fn baz(f: Foo) -> &i32
```
  """,
  """
```
fn baz<'a>(f: Foo<'a>) -> &i32
```
  """,
  """
```
fn baz<'a>(f: Foo) -> &'a i32
```
  """,

]
prompt.answerIndex = 4
context = """
Struktura przyjmuje jeden parametr czasu życia, a wynik ma jeden czas życia, więc Rust zakłada, że są one takie same.
"""

[[questions]]
id = "d03748df-8dcf-4ec8-bd30-341927544665"
type = "MultipleChoice"
prompt.prompt = """
Rozważ następującą sygnaturę funkcji bez adnotacji.

```
struct Foo<'a> {
  bar: &'a i32
}

// Foo changed to &Foo
fn baz(f: &Foo) -> &i32 { /* ... */ }
```

Czy Rust zaakceptuje tę sygnaturę funkcji? Jeśli tak, jakie czasy życia wywnioskuje?
"""
answer.answer = "Rust odrzuci tę sygnaturę funkcji"
prompt.distractors = [  
  """
```
fn baz(f: &Foo) -> &i32
```
  """,
  """
```
fn baz<'a>(f: &Foo<'a>) -> &'a i32
```
  """,
  """
```
fn baz<'a>(f: &'a Foo) -> &'a i32
```
  """,
  """
```
fn baz<'a, 'b>(f: &'a Foo<'b>) -> &'a i32
```
  """,
  """
```
fn baz<'a, 'b>(f: &'a Foo<'b>) -> &'b i32
```
  """
]
prompt.answerIndex = 0
context = """
Rust nie skompiluje tego programu, ponieważ nie jest jednoznaczne, czy czas życia wyniku jest powiązany
z czasem życia `&Foo`, czy referencji `Foo.bar`.
"""
