[[questions]]
id = "affe428d-0a8e-430b-9567-99e6b7563c0f"
type = "MultipleChoice"
prompt.prompt = """
Które z poniższych działań może nie działać poprawnie, jeśli wykonuje je wiele testów, a `cargo test` uruchamiasz bez dodatkowej konfiguracji?
"""
answer.answer = "Zapisywanie tekstu do jednego pliku"
prompt.distractors = [
  "Wypisywanie łańcuchów na standardowe wyjście",
  "Kończenie niepowodzeniem przez panikę",
  "Odczytywanie danych z jednej bazy danych"
]
context = """
Testy domyślnie działają równolegle, więc działania, które nie są bezpieczne wątkowo (jak zapis do jednego pliku), mogą prowadzić do wyścigu.
"""

[[questions]]
id = "19e292f4-4bc4-4868-a58a-edf62c3e3b2a"
type = "ShortAnswer"
prompt.prompt = """
Rozważ program z następującymi testami jednostkowymi:

```
#[test]
fn test_the_logger() { /* ... */ }

#[test]
fn test_the_database() { /* ... */ }

#[test]
fn test_logger_and_database() { /* ... */ }
```

Jaki jest *najkrótszy* łańcuch, który możesz przekazać do `cargo test <the_string>`, aby uruchomione zostały *tylko* `test_the_logger` i `test_the_database`?
"""
answer.answer = "h"
context = """
Najkrótszym podłańcuchem, który nie występuje w `test_logger_and_database`, ale występuje w `test_the_logger` i `test_the_database`,
jest „h” (środkowy znak „the”).
"""
