[[questions]]
id = "3da96b29-d975-4cd8-a8eb-b1a6bd9b5c0a"
type = "MultipleChoice"
prompt.prompt = """
Który z poniższych powodów NIE jest dobrym powodem, by umieszczać testy jednostkowe w `#[cfg(test)] mod tests { ... }`?
"""
answer.answer = "Daje to testom dostęp do funkcji prywatnych"
prompt.distractors = [
  "Może to zmniejszyć rozmiar artefaktów generowanych przez kompilator",
  "Może to skrócić czas kompilacji",
  "Oddziela to testowe funkcje pomocnicze od kodu biblioteki"
]
context = """
Wszystkie testy jednostkowe w danym pliku mają dostęp do funkcji prywatnych tego pliku, niezależnie od tego, czy znajdują się w `mod tests`, czy nie.
"""
