[[questions]]
id = "7a7bb518-b06e-4756-9510-6a8d0d1c84fa"
type = "ShortAnswer"
prompt.prompt = "Jaką adnotację dodajesz do funkcji, aby wskazać, że jest ona testem jednostkowym?"
answer.answer = "#[test]"
context = """
Informuje ona środowisko testowe Cargo, że ma traktować tę funkcję jako test, a nie jako kod biblioteki.
"""

[[questions]]
id = "cd77485f-723a-4978-8da6-c4ca3df44c44"
type = "MultipleChoice"
prompt.prompt = """
Załóżmy, że masz funkcję o sygnaturze typu:

```
fn f(x: usize) -> Result<usize, String>;
```

i chcesz przetestować, że `f(0)` powinno zwrócić `Err(_)`.
Który z poniższych sposobów NIE jest poprawnym sposobem przetestowania tego?
"""
answer.answer = """
```
#[test]
#[should_err]
fn test() -> Result<usize, String> {
  f(0)
}
```
  """
prompt.distractors = [
  """
```
#[test]
fn test() {
  assert!(f(0).is_err());
}
```
  """,
  """
```
#[test]
#[should_panic]
fn test() { 
  f(0).unwrap();
}
```
  """,
  """
```
#[test]
fn test() {
  assert!(match f(0) {
    Ok(_) => false,
    Err(_) => true
  });  
}
```
  """
]
context = """
`should_err` nie istnieje w Ruście – każdy test, który zwraca `Result`, musi zwrócić `Ok`, aby przejść.
"""