[[questions]]
id = "e6cbd582-9692-4045-a984-8770a12e1b95"
type = "MultipleChoice"
prompt.prompt = """
Które z poniższych zdań najlepiej wyjaśnia, dlaczego Rust wnioskuje typy argumentów i wartości zwracanych dla domknięć, ale nie dla funkcji najwyższego poziomu?
"""
answer.answer = "Funkcje najwyższego poziomu mogą być częścią zewnętrznego interfejsu biblioteki, a domknięć nie da się bezpośrednio udostępnić"
prompt.distractors = [
  "Z powodu problemu stopu wywnioskowanie przez Rusta typów funkcji najwyższego poziomu jest matematycznie niemożliwe",
  "Ze względu na wsteczną zgodność ze starszymi wersjami Rusta",
  "Typy można wywnioskować dla wszystkiego, co da się przypisać do zmiennej, a funkcji najwyższego poziomu nie da się przypisać do zmiennej"
]
context = """
Teoretycznie Rust mógłby zapewniać wnioskowanie typów dla funkcji najwyższego poziomu. Języki funkcyjne, takie jak Haskell i OCaml, mają ten mechanizm.
Projektanci Rusta świadomie zdecydowali jednak, że funkcje najwyższego poziomu wymagają adnotacji typów, aby zwiększyć przejrzystość
na poziomie interfejsu: funkcja zawsze ma dokładnie taki typ, jaki deklaruje.
"""

[[questions]]
id = "f844d1c2-3f63-4cdb-b16e-6e818e996e0d"
type = "MultipleChoice"
prompt.prompt = """
Rust pozwala na dopasowywanie wzorców w argumentach domknięć, w tym na użycie podkreślenia. Możesz na przykład napisać:

```rust
let f = |_| (); // sometimes called the "toilet closure"
let s = String::from("Hello");
f(s);
```

Które z poniższych zdań najlepiej opisuje relację między `f` a `s` w tym programie?
"""
answer.answer = "`f` powoduje natychmiastowe zwolnienie `s`"
prompt.distractors = [
  "`f` nie ma wpływu na `s`",
  "`f` odczytuje `s`, a następnie odrzuca wynik",
  "`f` przechwytuje `s` do swojego środowiska"
]
context = """
„Domknięcie-toaleta” (*toilet closure*) przypomina [`std::mem::drop`](https://doc.rust-lang.org/std/mem/fn.drop.html), czyli funkcję, która przenosi
argument i powoduje jego zwolnienie.
"""