[[questions]]
id = "d50dd9fb-f84c-4748-9e45-cd3dc8d5fb47"
type = "MultipleChoice"
prompt.prompt = """
Które z poniższych zdań najlepiej opisuje, dlaczego o iteratorach mówi się, że są „leniwe”?
"""
answer.answer = "Iterator nie ma żadnego efektu, dopóki nie wywołasz metod, które pobierają z niego elementy"
prompt.distractors = [
    "Iterator tworzy kopię każdego elementu, po którym iteruje", 
    "Iterator przejmuje własność sekwencji elementów, po której iteruje", 
    "Iterator przejdzie tylko po określonej liczbie elementów"
]
context = """
„Leniwy” oznacza zazwyczaj „nie wykonuje pracy, dopóki go o to nie poproszono”, a iteratory nie wykonują żadnych
obliczeń, dopóki nie zostanie wywołana metoda `Iterator::next`.
"""

[[questions]]
id = "19eac65e-44ad-4349-9632-47bdbb519d46"
type = "MultipleChoice"
prompt.prompt = """
Prawda czy fałsz: te dwa fragmenty kodu są semantycznie równoważne, gdy `iter` jest iteratorem.

Fragment 1:
```
while let Some(x) = iter.next() {
    f(x);
}
```

Fragment 2:
```
for x in iter {
    f(x);
}
```
"""
answer.answer = "Prawda"
prompt.distractors = ["Fałsz"]
context = """
Pętla for jest lukrem składniowym dla `while let`, które samo jest lukrem dla `loop` i `break`.
"""

[[questions]]
id = "ff652580-b487-4379-bd70-652f5803321d"
type = "Tracing"
prompt.program = """
fn main() {
    let v = vec![1, 2, 3, 4];
    let a: Vec<_> = v.iter().filter(|x: &&i32| *x % 2 == 0).map(|x: &i32| x * 2).collect();
    let b: Vec<_> = v.iter().map(|x: &i32| x * 2).filter(|x: &i32| x % 2 == 0).collect();
    println!("{} {}", a[0], b[0]);
}
"""
answer.doesCompile = true
answer.stdout = "4 2"
context = """
Kolejność adapterów iteratora ma znaczenie &mdash; filter, a potem map, to nie to samo co map, a potem filter!

Być może zastanawiasz się, dlaczego pierwszy filter używa `*x`, a drugi nie.
`v.iter()` tworzy `Iterator<Item = &i32>`. Wywołanie `.filter()` przyjmuje na wejściu `Iterator<Item = T>`
i przekazuje swojemu predykatowi `&T`. Dlatego w wierszu 3 mamy `x: &&i32`. Biblioteka standardowa Rusta implementuje
operator reszty z dzielenia `%` dla `&i32` po lewej stronie ([zob. dokumentację](https://doc.rust-lang.org/std/ops/trait.Rem.html#impl-Rem%3Ci32%3E-for-%26'a+i32)),
ale nie dla `&&i32`. Musimy więc raz wykonać dereferencję `x`, aby użyć go w wyrażeniu `*x % 2`.

Z kolei w wierszu 4, gdy `.map()` przyjmuje na wejściu `Iterator<Item = T>`, przekazuje swojemu domknięciu `T`.
Dlatego domknięcie w `map` przyjmuje na wejściu `&i32`. Operator mnożenia `*` jest zaimplementowany dla `&i32`,
więc w `x * 2` nie trzeba wykonywać dereferencji `x`. Operacja `x * 2` daje wartość typu `i32`, więc
wynikiem map jest `Iterator<Item = i32>`. Następnie `filter` przyjmuje `x : &i32`, który również nie wymaga
dereferencji, aby obliczyć `x % 2`. Teraz już wiesz!
"""
