[[questions]]
id = "c753bc38-0dc1-44d5-8b06-136fdbbc26d2"
type = "MultipleChoice"
prompt.prompt = """
Którego profilu domyślnie używa `cargo build` uruchomione bez dodatkowych flag?
"""
answer.answer = "`dev`"
prompt.distractors = [
    "`release`",
    "`build`",
]
context = """
Aby skrócić czas kompilacji, domyślnym profilem jest `dev`. Jeśli chcesz użyć profilu `release`, który kompiluje się
dłużej, ale daje szybciej działający kod, dodaj `--release`. (Profil `build` nie istnieje).
"""
