[[questions]]
id = "20846719-fe7b-48b8-abfd-9c5f1174472f"
type = "MultipleChoice"
prompt.prompt = """
Rozważ przestrzeń roboczą o następującej strukturze:

```
├── Cargo.lock
├── Cargo.toml
└── crates
    ├── a
    |   ├── lib.rs
    |   └── Cargo.toml
    └── b
        ├── lib.rs
        └── Cargo.toml
```

Poszczególne pliki mają następującą zawartość:

```
// crates/b/lib.rs
pub fn f() {}
```

```toml
# crates/a/Cargo.toml
[dependencies]
b = {path = "../b"}
```

Która z poniższych ścieżek jest poprawnym odwołaniem do `f` wewnątrz `a/lib.rs`?
"""
answer.answer = "`b::f`"
prompt.distractors = [
    "`crates::b::f`",
    "`workspace::b::f`",
    "`super::b::f`",
]
context = """
Z perspektywy `a` crate `b` jest zewnętrznym crate’em jak każdy inny, więc do jego elementów odwołujesz się bez żadnego przedrostka.
"""

[[questions]]
id = "bc8a69b2-d9a8-4438-8657-391c3fda5ed9"
type = "ShortAnswer"
prompt.prompt = """
Rozważ przestrzeń roboczą z trzema pakietami: `a`, `b` i `c`. Ich manifesty wyglądają następująco:

```toml
# a/Cargo.toml
[dependencies]
rand = "0.8.4"

# b/Cargo.toml
[dependencies]
rand = "0.7.3"

# c/Cargo.toml
[dependencies]
rand = "0.8.5"
```

Ile różnych wersji `rand` zostanie użytych podczas kompilacji wszystkich pakietów przestrzeni roboczej?
Podaj odpowiedź jako cyfrę, np. 0, 1 itd.
"""
answer.answer = "2"
context = """
Zgodnie z regułami wersjonowania semantycznego `a` i `c` będą współdzielić najnowszą poprawkę wersji pomniejszej `0.8`.
`b` użyje najnowszej poprawki wersji pomniejszej `0.7`. Łącznie zostaną więc użyte dwie wersje.
"""