[[questions]]
id = "7e4eeb62-55c2-443b-a8cc-fba060501245"
type = "MultipleChoice"
prompt.prompt = """
Załóżmy, że publikujesz bibliotekę `foobar v0.1.0`. Po uruchomieniu `cargo publish` zauważasz błąd w jednej
z funkcji. Która z poniższych odpowiedzi najlepiej opisuje, jak nadpisać opublikowany crate w tej samej wersji `v0.1.0`?
"""
answer.answer = "Nie da się nadpisać opublikowanego crate’a w danej wersji"
prompt.distractors = [
    "Dodać flagę `--overwrite-published` do polecenia `cargo publish`",
    "Zalogować się do crates.io i usunąć wersję `v0.1.0` opublikowanego crate’a",   
    "Uruchomić `cargo yank`, a następnie `cargo publish`"
]
context = """
Crates.io nie pozwala nadpisywać opublikowanych wersji. Najlepszym wyjściem w takiej sytuacji jest wycofanie wadliwej wersji
i opublikowanie nowej, np. `v0.1.1`.
"""

[[questions]]
id = "84ac16a8-2460-4baf-8913-06da6e3603e6"
type = "MultipleChoice"
prompt.prompt = """
Który z poniższych kroków NIE jest wymagany do opublikowania crate’a w crates.io?
"""
answer.answer = "Dodanie dokumentacji do każdej publicznej funkcji w crate’cie"
prompt.distractors = [
    "Dodanie licencji w sekcji `[package]` pliku `Cargo.toml`",    
    "Rejestracja i zalogowanie się w crates.io",
    "Wybranie nazwy crate’a, która nie jest zarejestrowana w crates.io"
]
context = """
Dodawanie dokumentacji do funkcji publicznych jest zdecydowanie zalecane, ale domyślnie nie jest wymagane. Jeśli
chcesz, aby Rust traktował nieudokumentowany kod jako błąd, możesz dodać następującą instrukcję w korzeniu biblioteki:

```
#![deny(missing_docs)]
```
"""