[[questions]]
id = "e2df0a8a-7bdd-40a3-9918-e4a856978cbb"
type = "MultipleChoice"
prompt.prompt = """
Załóżmy, że publikujesz bibliotekę i chcesz na początku pliku `lib.rs` napisać dokumentację całej biblioteki.
Dokumentacja powinna być poprzedzona następującą składnią komentarza:
"""
answer.answer = "`//!`"
prompt.distractors = [
    "`///`",
    "`//`",    
]
context = """
`//!` nadaje się do dokumentacji na poziomie modułu, a `///` służy do dokumentowania pojedynczych elementów, takich jak funkcje.
"""

[[questions]]
id = "cfb65011-0578-4032-8aaa-b346b091602b"
type = "MultipleChoice"
prompt.prompt = """
Załóżmy, że tworzysz bibliotekę `worldly` z następującą funkcją w `lib.rs`:

    /// Adds the string "world" to `s`.
    ///
    /// # Example
    /// ```
    /// let mut s = String::new();
    /// worldly::add_world(&mut s);
    /// assert_eq!(s, "Hello world");
    /// ```
    pub fn add_world(s: &mut String) {
        s.push_str("world");
    }

    #[test]
    fn test_add_world() {
        let mut s = String::new();
        add_world(&mut s);
        assert_eq!(s, "world");
    }

Czy po uruchomieniu `cargo test` któryś test zakończy się niepowodzeniem?
"""
answer.answer = "Tak"
prompt.distractors = [
    "Nie",    
]
context = """
Niepoprawny przykład zostanie uruchomiony jako test dokumentacyjny i spowoduje niepowodzenie `cargo test`.
"""
