[[questions]]
id = "8282968d-b1d3-42b4-b128-f97b951db4c6"
type = "Tracing"
prompt.program = """
struct Example(i32);
impl Drop for Example {
    fn drop(&mut self) {
        self.0 += 1;
        println!("drop {}", self.0);
    }
}
fn main() {
    let e = Example(0);
    drop(e);
    drop(e);
}
"""
answer.doesCompile = false
answer.lineNumber = 11
context = """
Wartości, której jesteśmy właścicielem, nie można zwolnić dwukrotnie, więc drugie wywołanie drop jest błędem kompilacji.
"""

[[questions]]
id = "b9121273-1c1e-4e99-9cff-a23f845aaeeb"
type = "MultipleChoice"
prompt.prompt = """
Rozważ ten fragment kodu, który alokuje łańcuch znaków:

```rust
fn main() {
    let mut s = String::new();
    ____
}
```

Które z poniższych operacji można poprawnie wstawić w miejsce podkreślenia, aby spowodować zwolnienie `s`?
"""
answer.answer = ["`drop(s);`", "`(|_| ())(s);`", "`{ s };`"]
prompt.distractors = [
    "`s.drop();`",    
]
context = """
Każde użycie `s`, które ją przenosi i odrzuca wynik, spowoduje zwolnienie `s`. Natomiast `s.drop()` nie można
wywołać bezpośrednio.
"""