[[questions]]
id = "e127342d-7ad2-4730-b930-774411e1872d"
type = "Tracing"
prompt.program = """
use std::rc::Rc;
fn main() {
    let n = Rc::new(1);
    let mut n2 = Rc::clone(&n);
    *n2 += 1;
    println!("{}", n);
}
"""
answer.doesCompile = false
answer.lineNumber = 5
context = """
Danych wewnątrz `Rc` nie można modyfikować bez użycia wewnętrznej mutowalności (omówionej w następnym podrozdziale). `Rc` egzekwuje tę właściwość,
implementując trait `Deref`, ale nie implementując traitu `DerefMut`.
"""

[[questions]]
id = "3b43eb45-3400-4555-b605-9ae1cde7c80c"
type = "Tracing"
prompt.program = """
use std::rc::Rc;
struct Example;
impl Drop for Example {
    fn drop(&mut self) {
        println!("drop");
    }
}
fn main() {
    let x = Rc::new(Example);    
    let y = Rc::clone(&x);    
    println!("A");
    drop(x);
    println!("B");
    drop(y);    
    println!("C");
}
"""
answer.doesCompile = true
answer.stdout = """
A
B
drop
C
"""
context = """
Wartość wewnątrz wskaźnika ze zliczaniem referencji zostaje zwolniona tylko raz, więc napis „drop” pojawia się tylko raz.
Pierwsze `drop(x)` zmniejsza licznik referencji, ale nie zwalnia wartości, ponieważ `y` wciąż żyje.
Następnie przy zwalnianiu `y` okazuje się, że licznik referencji wynosi 0, więc `Example` zostaje zwolniony.
"""