[[questions]]
id = "01904807-74c7-41ad-8d8b-cfb30e5ce10c"
type = "MultipleChoice"
prompt.prompt = """
Który z poniższych opisów najlepiej oddaje pojęcie *wewnętrznej mutowalności* w Ruście?
"""
answer.answer = "Umożliwienie modyfikowania danych przez niemutowalną referencję"
prompt.distractors = [
    "Opakowanie kodu `unsafe` w bezpieczne API",
    "Umożliwienie modyfikowania danych znajdujących się wewnątrz struktury danych",
    "Używanie borrow checkera do zapewniania bezpieczeństwa pamięci w czasie działania"
]
context = """
Główna idea wewnętrznej mutowalności polega na tym, że mając wartość typu `&T`, można
bezpiecznie modyfikować dane wewnątrz `T`.
"""

[[questions]]
id = "380cd865-76c5-419c-8961-af4c59d2ab71"
type = "MultipleChoice"
prompt.prompt = """
Rozważ API, które zlicza wywołania określonej metody:

```
struct Api {
    count: ???
}

impl Api {
    fn some_method(&self) {
        // increment count
        // rest of the method...
    }    
}
```

Załóżmy, że licznik jest reprezentowany jako `usize`. Który z poniższych typów opakowujących
byłby najodpowiedniejszy w tej sytuacji?
"""
answer.answer = "`RefCell<usize>`"
prompt.distractors = [
    "`Rc<usize>`",
    "`Box<usize>`",
    "Żaden, `usize` wystarczy"
]
context = """
`RefCell` przydaje się tutaj do modyfikowania wewnętrznego pola, mimo że `some_method` przyjmuje
na wejściu niemutowalną referencję. Jeśli wewnętrzne pole jest zwykłą liczbą całkowitą, jeszcze lepszym
wyborem typu byłby `Cell<usize>` albo `AtomicUsize`.
"""

[[questions]]
id = "d4ae1b8e-79a7-4485-828f-fb30cdeb29d5"
type = "MultipleChoice"
prompt.prompt = """
Rozważ następującą niepoprawną implementację `RefCell`, która nie sprawdza,
czy wewnętrzna wartość jest pożyczona:

```
use std::cell::UnsafeCell;
struct BadRefCell<T>(UnsafeCell<T>);
impl<T> BadRefCell<T> {
    pub fn borrow_mut(&self) -> &mut T {
        unsafe { &mut *self.0.get() }
    }
}
```

Załóżmy teraz, że mamy taki `BadRefCell`:

```
let v = BadRefCell(UnsafeCell::new(vec![1, 2, 3]));
```

Który z poniższych fragmentów naruszyłby bezpieczeństwo pamięci przy użyciu tego API?
"""
answer.answer = """
```
let v1 = v.borrow_mut();
let n = &v1[0];
v.borrow_mut().push(0);
println!("{n}");
```
"""
prompt.distractors = [
"""
```
drop(v.borrow_mut());
drop(v.borrow_mut());
```
""",
"""
```
let v1 = v.borrow_mut();
let v2 = v.borrow_mut();
v1.push(0);
v2.push(0);
```
""",
"""
```
v.borrow_mut().push(0);
let n = v.borrow_mut()[0];
println!("{n}");
```
"""
]
context = """
`BadRefCell` pozwala nam mieć jednocześnie dwie mutowalne referencje do danych wewnętrznych,
co umożliwia naruszenie bezpieczeństwa pamięci, takie jak realokacja wektora przy jednoczesnym
przechowywaniu referencji do jego zawartości.
"""
