[[questions]]
id = "6f3c2a68-24f7-439b-9fe0-426abd27e487"
type = "Tracing"
prompt.program = """
fn main() {
    let mut n = 1;
    let b = Box::new(&mut n);
    **b += 1;
    println!("{}", n);
}
"""
answer.doesCompile = true
answer.stdout = "2"
context = """
Box może przechowywać referencję mutowalną, więc dwukrotna dereferencja `b` prowadzi z powrotem do `n`.
"""

[[questions]]
id = "57595a80-c79f-4aae-a1d4-cdaf212d7c21"
type = "ShortAnswer"
prompt.prompt = """
Załóżmy, że mamy program ze zmienną:

```
let x: [Box<(usize, usize)>; 4] = /* ... */
```

Jaki jest minimalny możliwy rozmiar w pamięci (w bajtach) zmiennej `x` na stosie przy kompilacji na platformę o architekturze 64-bitowej?
Wpisz odpowiedź cyframi, np. 0, 1 itd.
"""
answer.answer = "32"
context = """
Box zawiera wskaźnik, który w architekturze 64-bitowej zajmuje 8 bajtów. Tablica 4 wskaźników zajmuje więc co najmniej 4 * 8 = 32 bajty.
"""