[[questions]]
id = "43081862-aac8-4e18-9c55-1107ea4c7cc1"
type = "MultipleChoice"
prompt.prompt = """
Wyobraź sobie, że projektujesz API dla połączenia z bazą danych, na przykład takie:

```
struct DbConnection { /* ... */ }
impl DbConnection {
    fn query(&self) -> DbResult {
        /* ... */
    }
}
```

Twoja baza danych nie obsługuje współbieżnych zapytań z tego samego połączenia.
Które z poniższych traitów znacznikowych powinien implementować `DbConnection`?
"""
answer.answer = "`Send`"
prompt.distractors = [
    "`Send` i `Sync`",
    "`Sync`",
    "Ani `Send`, ani `Sync`"
]
context = """
Przesyłanie `DbConnection` między wątkami jest w porządku, więc `DbConnection` powinien implementować `Send`.
Nie byłoby jednak poprawne np. współdzielenie `Arc<Database>` w taki sposób, by wiele wątków współbieżnie
wywoływało `db.query()`, więc `DbConnection` nie powinien implementować `Sync`.
"""