[[questions]]
id = "ceb96826-6c98-40e1-bff4-0bb61f35679d"
type = "MultipleChoice"
prompt.prompt = """
W niektórych API współbieżności mutex jest oddzielony od danych, których strzeże. Wyobraź sobie na przykład hipotetyczne API mutexu takie jak to:

```
let mut data = Vec::new();
let mx: Mutex = Mutex::new();
{
    let _guard = mx.lock();
    data.push(0);
}
```

Które z poniższych zdań najlepiej opisuje, dlaczego Rust używa `Mutex<T>` zamiast samego `Mutex`?
"""
answer.answer = "Aby uniemożliwić dostęp do danych mutexu bez zablokowania mutexu"
prompt.distractors = [
    "Aby wymagać mniejszej liczby wywołań metod mutexu",
    "Aby poprawić wydajność programów współbieżnych korzystających z mutexów",
    "Aby uniemożliwić przenoszenie danych mutexu między wątkami"
]
context = """
Konstrukcja `Mutex<T>` gwarantuje, że dostęp do danych mutexu jest możliwy tylko wtedy, gdy mutex jest zablokowany, i odwrotnie:
że mutex zostaje odblokowany, gdy dane przestają być dostępne.
"""

[[questions]]
id = "e5ac0c92-4694-4647-bd20-67825fe038b7"
type = "Tracing"
prompt.program = """
use std::{sync::Arc, thread};

fn main() {
    let s = String::from("Hello world");
    let a = Arc::new(&s);
    let a2 = Arc::clone(&a);
    let t = thread::spawn(move || a2.len());
    let len = t.join().unwrap();
    println!("{} {}", a, len);
}
"""
answer.doesCompile = false
answer.lineNumber = 7
context = """
`Arc` nadal nie jest bezpieczny w użyciu, jeśli jego dane zawierają referencję, ponieważ referencja mogłaby (teoretycznie)
stać się nieważna, zanim wszystkie wątki zawierające `Arc` zakończą działanie.
"""