[[questions]]
id = "d19f9e83-d4c2-41d5-9fc7-81db5135eb1e"
type = "MultipleChoice"
prompt.prompt = """
W przykładzie omawianym w tym podrozdziale wpis na blogu mógł być w jednym z trzech stanów: `Draft`, `PendingReview` lub `Published`. Każdy stan był reprezentowany przez strukturę, a przejścia między stanami – przez metody traitu zwracające obiekty traitów.

W alternatywnej implementacji stany można by reprezentować za pomocą enuma, na przykład tak:

```
enum BlogState {
    Draft,
    PendingReview,
    Published
}

impl Post {
    fn request_review(&mut self) {
        use BlogState::*;
        self.state = match self.state {
            Draft => PendingReview,
            PendingReview => PendingReview,
            Published => Published
        }
    }
}
```

Które z poniższych powodów przemawiają za wyborem reprezentacji opartej na strukturach i traitach zamiast reprezentacji opartej na enumie?
"""
answer.answer = [
    "Klient API mógłby dodać do systemu nowy stan",
    "Dodanie nowego stanu nie wymaga modyfikowania metod we wszystkich pozostałych stanach"
]
prompt.distractors = [
    "Użycie `match` jest w czasie działania wolniejsze niż dynamiczne wywoływanie",
    "Klient API mógłby dodać nową metodę dla wszystkich stanów w systemie"
]
context = """
Podejście oparte na strukturach i traitach jest rozszerzalne w tym sensie, że klient API mógłby
utworzyć nowy stan (na przykład `Retracted`) bez zmieniania podstawowej funkcjonalności API. Przy
dodawaniu takiego stanu nie trzeba zmieniać metod pozostałych stanów. Natomiast w przypadku enumów
klient nie może dodać nowego wariantu do enuma. Co więcej, po dodaniu stanu trzeba zaktualizować
wszystkie wyrażenia `match`.

Wyrażenie `match` raczej nie będzie wolniejsze niż dynamiczne wywoływanie. Takie wyrażenie to proste
rozgałęzienie na podstawie znacznika enuma, natomiast dynamiczne wywoływanie wymaga dodatkowego poziomu
pośredniości – przez tablicę metod wirtualnych obiektu traitu – i wywołań funkcji, które nie są
wstawiane w miejsce wywołania (*inlining*).

W podejściu opartym na strukturach i traitach klient API nie może dodać nowej *metody* dla
istniejących stanów – może jedynie dodawać nowe stany. Metody są ustalone przez definicję traitu
napisaną przez autora API. Zwróć uwagę, że można dodać nową metodę, która jedynie korzysta z
istniejących metod, za pomocą traitów rozszerzających (*extension traits*), na przykład:

```
trait StateExt {
    fn request_review_twice(self: Box<Self>) -> Box<dyn State>;
}

impl<S: State> StateExt for S {
    fn request_review_twice(self: Box<Self>) -> Box<dyn State> {
        self.request_review().request_review()
    }
}
```

Takie rozszerzenia nie mają jednak dostępu do prywatnych danych stanów.
"""
