[multipart]
q = """
**Kontekst:** projektujesz prosty system zdarzeń, który wywołuje funkcje zwrotne (*callbacks*) w odpowiedzi na zdarzenia.

**Funkcjonalność:** struktura `Events` udostępnia funkcje do rejestrowania funkcji zwrotnych.
Funkcja zwrotna jest albo równoległa (może działać na wielu wątkach), albo sekwencyjna (musi działać wyłącznie w wątku głównym).

**Rozwiązania:** poniżej znajduje się kilka proponowanych rozwiązań realizujących tę funkcjonalność.

```
pub struct Events {
	// ...
}

// Option 1: parallel and sequential are two separate methods
impl Events {
	pub fn register<E, F: Fn(E)>(&mut self, f: F) { /* .. */ }
	pub fn register_sequential<E, F: Fn(E)>(&mut self, f: F) { /* .. */ }
}

// Option 2: parallel and sequential are two members of an enum
pub enum Callback<F> {
	Parallel(F),
	Sequential(F)
}
impl Events {
	pub fn register<E, F: Fn(E)>(&mut self, f: Callback<F>) { /* .. */ }
}

// Option 3: parallel and sequential are markers in a trait method
pub trait Register<Marker, F, E> {
	fn register(&mut self, f: F);
}
pub struct Parallel;
pub struct Sequential;
impl<F, E> Register<Parallel, F, E> for Events 
where F: Fn(E) {
	fn register(&mut self, f: F) { /* .. */ }
}
impl<F, E> Register<Sequential, F, E> for Events 
where F: Fn(Sequential, E) {
	fn register(&mut self, f: F) { /* .. */ }
}
```
"""

[[questions]]
type = "MultipleChoice"
multipart = "q"
prompt.prompt = """
Zaznacz każdą opcję projektową, która spełnia następujące wymaganie:

**Wymaganie:** funkcja zwrotna powinna być domyślnie traktowana jako równoległa, a API powinno odzwierciedlać to domyślne zachowanie.
"""
prompt.distractors = ["2"]
prompt.sortAnswers = true
answer.answer = ["1", "3"]
context = """
Najpierw wyobraźmy sobie, jak wyglądałaby rejestracja funkcji zwrotnej w każdym z rozwiązań.

```rust
// Option 1
events.register(|e: OnClick| { /* .. */ });
events.register_sequential(|e: OnClick| { /* .. */ })

// Option 2
events.register(Callback::Parallel(|e: OnClick| { /* .. */ }));
events.register(Callback::Sequential(|e: OnClick| { /* .. */ }));

// Option 3
events.register(|e: OnClick| { /* .. */ });
events.register(|_: Sequential, e: OnClick| { /* .. */ });
```

Spośród nich opcje 1 i 3 komunikują, że tryb równoległy jest domyślny, ponieważ odpowiada najprostszemu wariantowi.
Tryb sekwencyjny wymaga albo dłuższej nazwy metody (`_sequential`), albo typu znacznikowego (`_: Sequential)`.

Opcja 2 nie zaznacza wyraźnie, że tryb równoległy powinien być domyślny, ponieważ zarówno `Parallel`, jak i `Sequential` trzeba jawnie
przekazywać do `register`.
"""
id = "4a32bad8-fee7-45b5-80ef-775d059aab48"

[[questions]]
type = "MultipleChoice"
multipart = "q"
prompt.prompt = """
Zaznacz każdą opcję projektową, która spełnia następujące wymaganie:

**Wymaganie:** API powinno eksportować jak najmniej metod.
"""
prompt.distractors = ["1"]
prompt.sortAnswers = true
answer.answer = ["2", "3"]
context = """
Opcje 2 i 3 eksportują tylko jedną metodę `register`. Opcja 1 wymaga wyeksportowania dwóch metod rejestrujących o różnych nazwach.
"""
id = "eaeafdad-ac3a-4d92-85eb-995991a81c2d"


[[questions]]
multipart = "q"
type = "MultipleChoice"
prompt.prompt = """
Zaznacz każdą opcję projektową, która spełnia następujące wymaganie:

**Wymaganie:** API powinno jak najmniej polegać na mechanizmie wnioskowania typów kompilatora.
"""
prompt.distractors = ["3"]
prompt.sortAnswers = true
answer.answer = ["1", "2"]
context = """
Opcje 1 i 2 nie wymagają wiele wnioskowania typów poza ustaleniem typu funkcji `F`.

Opcja 3 stosuje sztuczkę z przeciążaniem: tworzy trait `Register` sparametryzowany typem „znacznikowym”.
Przypomnij sobie jej dwa wywołania rejestrujące:
```
events.register(|e: OnClick| { /* .. */ })
events.register(|_: Sequential, e: OnClick| { /* .. */ })
```

Wyglądają, jakby używały tej samej implementacji, ale w rzeczywistości odnoszą się do różnych implementacji tej samej metody.
To rozwiązanie polega na tym, że kompilator wywnioskuje typ `Marker`, ustalając, której implementacji `Register`
odpowiada każde wywołanie `.register(..)`. Dlatego jeśli naszym celem jest *nie* polegać na wnioskowaniu typów, opcja 3 jest nieodpowiednia.
"""
id = "e0c4f766-b82a-496a-b669-ea9e0a367af7"