[multipart]
q = """
**Kontekst:** projektujesz bibliotekę serializacji, która konwertuje typy danych Rusta na formaty takie jak JSON.

**Funkcjonalność:** trait `Serialize`, który mogą implementować typy serializowalne, oraz funkcja `to_json`, która konwertuje typy serializowalne na JSON.

**Rozwiązania:** poniżej znajduje się kilka proponowanych rozwiązań realizujących tę funkcjonalność.

```
// Option 1: types serialize to a `Value` enum
pub enum Value {
	String(String),
	Number(isize)
}

pub trait Serialize {
	fn serialize(&self) -> Value;
}

fn value_to_json(value: Value) -> String {
	/* .. */
}

pub fn to_json(data: impl Serialize) -> String {
    let value = data.serialize();
    value_to_json(value)
}


// Option 2: types serialize via calls to a `Serializer` interface
pub trait Serialize {
	fn serialize<S: Serializer>(&self, serializer: &mut S);
}

pub trait Serializer {
	fn serialize_string(&mut self, s: &str);
	fn serialize_number(&mut self, n: isize);
}

struct JsonSerializer { buffer: String };
impl Serializer for JsonSerializer {
	/* .. */
}

pub fn to_json(data: impl Serialize) -> String {
	let mut serializer = JsonSerializer { buffer: String::new() };
	data.serialize(&mut serializer);
	serializer.buffer
}
```
"""

[[questions]]
type = "MultipleChoice"
multipart = "q"
prompt.prompt = """
Zaznacz każdą opcję projektową, która spełnia następujące wymaganie:

**Wymaganie:** powinno być możliwe dodanie nowego formatu danych bez konieczności modyfikowania kodu w istniejących implementacjach traitu `Serialize`.
"""
prompt.distractors = []
prompt.sortAnswers = true
answer.answer = ["1", "2"]
context = """
Oba rozwiązania są wystarczająco od siebie oddzielone, by każdy nowy format danych był niezależny od jakichkolwiek implementacji `Serialize`. W opcji 1
każdy format danych konwertuje `Value` na reprezentację właściwą dla tego formatu. `Value` pełni rolę granicy modułu.

W opcji 2 nie ma jawnej reprezentacji pośredniej serializowanej wartości – zamiast tego każda implementacja `Serialize` jest jawnie generyczna
względem dowolnego `S`, który implementuje `Serializer`.
"""
id = "66e036c9-91a0-4611-8110-967b5ed1a514"

[[questions]]
type = "MultipleChoice"
multipart = "q"
prompt.prompt = """
Zaznacz każdą opcję projektową, która spełnia następujące wymaganie:

**Wymaganie:** proces serializacji powinien zużywać jak najmniej pamięci.
"""
prompt.distractors = ["1"]
prompt.sortAnswers = true
answer.answer = ["2"]
context = """
Opcja 1 serializuje dane, najpierw konwertując strukturę danych na reprezentację pośrednią `Value`, a następnie konwertując `Value` na format docelowy.
Ta pośrednia struktura danych zużywa pamięć, która nie jest potrzebna w opcji 2, gdzie dane są konwertowane bezpośrednio na format docelowy.
"""
id = "eaa95520-1b72-4f7d-a600-5444b6368785"


[[questions]]
multipart = "q"
type = "MultipleChoice"
prompt.prompt = """
Zaznacz każdą opcję projektową, która spełnia następujące wymaganie:

**Wymaganie:** serializowanie tego samego typu danych do wielu formatów powinno jak najmniej zwiększać rozmiar skompilowanego pliku binarnego.
"""
prompt.distractors = ["2"]
prompt.sortAnswers = true
answer.answer = ["1"]
context = """
W opcji 1 istnieje tylko jedna instancja `Serialize`, która konwertuje typ `T` na `Value`. Ponieważ opcja 2 jest generyczna względem serializatorów `S`,
za każdym razem, gdy `T::serialize` zostanie wywołane z nowym `S`, kompilator Rusta zmonomorfizuje nową instancję `T::serialize`, co zwiększy rozmiar
pliku binarnego w porównaniu z opcją 1.
"""
id = "2751731e-7d18-46a1-aaea-b5734bf51c80"
