[[questions]]
id = "a4680619-9533-4cbb-a785-7b73570168af"
type = "MultipleChoice"
prompt.prompt = """
Które z poniższych aspektów programowania obiektowego Rust implementuje?
"""
answer.answer = [
    "Obiekty z metodami",
    "Hermetyzację prywatnych danych",
]
prompt.distractors = [
    "Dziedziczenie metod nadklasy"
]
context = """
Rust ma obiekty (tj. struktury) i hermetyzację (dzięki słowu kluczowemu `pub`), ale nie ma dziedziczenia.
"""
