[[questions]]
id = "5dcd923f-13a4-4181-b252-4b580547249f"
type = "Tracing"
prompt.program = """
fn main() {
    let x = (0, 1);
    match x {
        (_, y) if y == 0 => println!("A"),
        (0, _) => println!("B"),
        _ => println!("C")
    }
}
"""
answer.doesCompile = true
answer.stdout = "B"
context = """
Pierwsze ramię dopasowuje `y = 1`, co oznacza, że `y != 0`, więc wzorzec nie pasuje.
Drugie ramię wymaga, aby `x == 0`, co jest prawdą, więc wzorzec pasuje.
"""

[[questions]]
id = "ac0045c7-981a-46cb-baeb-adaa533804ad"
type = "MultipleChoice"
prompt.prompt = """
Rozważ następujący program:

```
let a = [(0, 1)];
let ?? = a;
```

Które z poniższych są poprawnymi wzorcami, którymi można zastąpić symbol zastępczy `??`?
"""
answer.answer = [
    "`_`",
    "`[(n, ..)]`",
    "`[..]`"
]
prompt.distractors = [
    "`(_, n)`"
]
context = """ 
Wzorzec `(_, n)` jest niepoprawny, ponieważ `a` jest tablicą krotek, a nie krotką.
"""

[[questions]]
id = "0b0d90c3-c81b-4b81-9e1b-f8bd58a22c6c"
type = "Tracing"
prompt.program = """
fn main() {
    let x = Some(&[0, 1]);
    match x {
        Some(&[.., 1, ..]) => println!("A"),
        Some(&[0, 1]) | None => println!("B"),
        _ => println!("C")
    }
}
"""
answer.doesCompile = false
answer.lineNumber = 4
context = """
Nie można użyć `..` po obu stronach wartości, ponieważ nie wiadomo jednoznacznie,
o który element tablicy chodzi.
"""

[[questions]]
id = "a7d38ffa-66b2-472a-90a5-b026b28ad3df"
type = "MultipleChoice"
prompt.prompt = """
Załóżmy, że mamy typ `Point` z następującą definicją:

```
struct Point {
    x: i32,
    y: i32
}
```

Dany jest następujący wzorzec:

```
Point { x: x @ 0 ..= 5, y } if x + y != 0
```

Które z poniższych wartości pasują do tego wzorca?
"""
answer.answer = [
    "`Point { x: 5, y: -4 }`",
    "`Point { x: 0, y: 1 }`",
]
prompt.distractors = [
    "`Point { x: -1, y: 2 }`",
    "`Point { x: 3, y: -3 }`"
]
context = """
Ten wzorzec określa, że `x` musi mieścić się w przedziale od 0 do 5 (włącznie) oraz że `x + y != 0`.
Dlatego `(5, -4)` i `(0, 1)` pasują, a `(-1, 2)` i `(3, -3)` nie.
"""
