[[questions]]
id = "35e59c95-3d83-4277-8d88-a1986f4086d7"
type = "MultipleChoice"
prompt.prompt = """
Rozważ dopasowywanie wzorców do wyrażenia pewnego typu `T`.
Które z tych stwierdzeń najlepiej opisuje różnicę między wzorcem odrzucalnym a nieodrzucalnym?
"""
answer.answer = "Wzorce odrzucalne nie pasują do pewnej wartości typu `T`, a wzorce nieodrzucalne pasują do wszystkich wartości typu `T`"
prompt.distractors = [
    "Wzorce odrzucalne pasują do niektórych wartości innego typu `S`, a wzorce nieodrzucalne pasują tylko do wartości typu `T`",
    "Wzorce odrzucalne nie pasują do żadnej wartości typu `T`, a wzorce nieodrzucalne pasują do niektórych wartości typu `T`",
    "Wzorce odrzucalne to wzorce, w których `T` jest enumem, a wzorce nieodrzucalne to wzorce, w których `T` nie jest enumem"
]
context = """
Wzorzec jest odrzucalny, jeśli istnieje jakaś wartość oczekiwanego typu, która do niego nie pasuje.
"""

[[questions]]
id = "3c29eb2d-cbe9-4a2c-99b8-aa5c6467c8b4"
type = "MultipleChoice"
prompt.prompt = """
Rozważ następujący program:

```
let x: &[(i32, i32)] = &[(0, 1)];
```

Które z poniższych wzorców są **odrzucalne** dla `x`?
"""
answer.answer = [
    "`&[(x, y)]`",
    "`&[(x, y), ..]`",    
]
prompt.distractors = [
    "`&[..]`",
    "`_`"
]
context = """ 
Wycinek nie ma stałej długości, więc każdy wzorzec, który zakłada, że
`x` musi mieć co najmniej jeden element, jest odrzucalny.
"""
