[[questions]]
id = "f08ab588-1dca-438e-8108-a1b2410a4343"
type = "MultipleChoice"
prompt.prompt = """
Rozważ dwa sposoby zaimplementowania funkcji `register`, która przyjmuje funkcję zwrotną:

```
fn register1(cb: fn(Event) -> ());
fn register2<F>(cb: F) where F: Fn(Event) -> ();
```

Która sygnatura typu pozwala funkcji `register` przyjmować najbardziej różnorodne argumenty?
"""
answer.answer = "`register2`"
prompt.distractors = [
  "`register1`",
  "Są równoważne"
]
context = """
Do `register2` można przekazać domknięcia ze środowiskiem, natomiast do `register1` można przekazać tylko funkcje najwyższego poziomu (lub domknięcia bez środowiska).
"""