[[questions]]
id = "8c80f9e8-2d95-43cc-9aa4-04d617dd8cb9"
type = "Tracing"
prompt.program = """
macro_rules! manylet {
    ( $( $i:ident ),* = $e:expr ) => {
        $(
            let mut $i = $e;
        )*
    }
}

fn main() {
    let mut s = String::from("A");
    manylet!(x, y = s);
    x.push_str("B");
    println!("{x}{y}");
}
"""
answer.doesCompile = false
answer.lineNumber = 11
context = """
Makro `manylet` składniowo powiela wyrażenie `e` jako wiązanie dla każdej
zmiennej po lewej stronie znaku równości. Ponieważ jednak `s` jest łańcuchem będącym właścicielem swoich danych,
pierwsze wiązanie do `x` przenosi `s`, a drugie wiązanie do `y` jest niepoprawne.
"""

[[questions]]
id = "f4f664ef-4b0b-43ac-ba90-5051a4ef89fb"
type = "MultipleChoice"
prompt.prompt = """
Które z poniższych powodów są uzasadnione, by zaimplementować makro jako
makro proceduralne zamiast makra deklaratywnego?
"""
answer.answer = [
    "Chcesz zintegrować makro z systemem derive w Ruście",
    "Twoje makro wymaga nietrywialnej analizy składni napisanej przez użytkownika makra",
]
prompt.distractors = [
  "Chcesz generować sekwencje kodu o zmiennej długości",
  "Twoje makro wymaga na wejściu całego elementu, a nie tylko wyrażenia"
]
context = """
Makra proceduralne to jedyny sposób na utworzenie własnego derive. Makra proceduralne
przydają się też, gdy potrzebujesz kodu analizującego składnię użytkownika makra &mdash; makra
deklaratywne pozwalają jedynie przestawiać elementy wejścia, a nie np. obliczać jego rozmiar.

Makra deklaratywne potrafią generować sekwencje kodu o zmiennej długości i mogą opakowywać
lub tworzyć elementy, a nie tylko wyrażenia.
"""

[[questions]]
id = "4c7dce03-99c6-41e3-8482-ccf4e30974ff"
type = "MultipleChoice"
prompt.prompt = """
Które z poniższych zdań najlepiej opisuje wejście makra proceduralnego?
"""
answer.answer = "Wejściem jest sekwencja tokenów"
prompt.distractors = [
  "Wejściem jest otypowany graf przepływu sterowania",
   "Wejściem jest abstrakcyjne drzewo składni",
  "Wejściem jest łańcuch bajtów"
]
context = """
Makra proceduralne przyjmują na wejściu (i zwracają na wyjściu) strumienie tokenów.
Do przekształcania tokenów w drzewa składni możesz używać crate’ów takich jak `syn`.
"""