[[questions]]
id = "7859b06e-72ba-4c07-a3e2-b4f8cb7fd903"
type = "MultipleChoice"
prompt.prompt = """
Przypomnij sobie definicję traitu `Add`:

```
trait Add<Rhs=Self> {
    type Output;
    fn add(self, rhs: Rhs) -> Self::Output;
}
```

Które z poniższych zdań najlepiej wyjaśnia, dlaczego `Output` jest typem powiązanym, a `Rhs` parametrem typu?
"""
answer.answer = "Typ `T` powinien dać się dodawać do wielu innych typów `S`, ale dana operacja `T + S` powinna zawsze mieć jeden typ wyniku"
prompt.distractors = [
    "Operacja dodawania przyjmuje `Rhs` na wejściu i zwraca `Output` na wyjściu, a parametry typu służą do wejścia, natomiast typy powiązane do wyjścia",
    "Trait może mieć tylko jeden typ powiązany, więc `Rhs` musi być parametrem typu traitu `Add`",
    "Typ powiązany nie może mieć wartości domyślnej, a parametr typu traitu może ją mieć"
]
context = """
To prawda, że typ powiązany nie może obecnie mieć wartości domyślnej, ale nie jest to główny
powód, dla którego `Rhs` jest parametrem typu w traicie `Add`.
"""

[[questions]]
id = "d2c77d93-3887-40a2-b93a-501aa315d676"
type = "MultipleChoice"
prompt.prompt = """
Przypomnij sobie definicję traitu `Add`:

```
trait Add<Rhs=Self> {
    type Output;
    fn add(self, rhs: Rhs) -> Self::Output;
}
```

Które z poniższych zdań najlepiej wyjaśnia, dlaczego `Rhs` jest parametrem typu traitu `Add`, a nie funkcji `add`? Innymi słowy: dlaczego `Add` nie jest zaprojektowany tak:

```
trait Add {
    type Output;
    fn add<Rhs>(self, rhs: Rhs) -> Self::Output;
}
```
"""
answer.answer = "Gdyby `Rhs` był parametrem typu na poziomie funkcji, definicja `add` nie mogłaby zakładać żadnej struktury `Rhs`"
prompt.distractors = [
    "Sprawdzanie typów działa wydajniej, gdy `Rhs` jest parametrem typu na poziomie traitu, niż gdy jest parametrem typu na poziomie funkcji",
    "`Rhs` nie może mieć typu domyślnego jako parametr typu na poziomie funkcji",
    "Generowanie kodu dla funkcji `add` wymagałoby dodatkowego czasu na monomorfizację z powodu parametru typu na poziomie funkcji"
]
context = """
Taki projekt nie miałby większego sensu, ponieważ `add<Rhs>` nie miałaby żadnych informacji o
strukturze `Rhs`, więc nie dałoby się w ten sposób zaimplementować żadnej sensownej funkcji dodawania.
"""

[[questions]]
id = "79db9ca4-693f-4e62-8b8d-356b51a63006"
type = "Tracing"
prompt.program = """
mod inner {
    pub trait A {
        fn f(&self) -> usize { 0 }
    }
    pub trait B {
        fn f(&self) -> usize { 1 }
    }
    pub struct P;
    impl A for P {}
    impl B for P {}
}
fn main() {
    use inner::{P, B};    
    println!("{}", P.f());    
}
"""
answer.doesCompile = true
answer.stdout = "1"
context = """
Gdy zaimportowana jest tylko jedna z dwóch kolidujących implementacji traitów, Rust używa
zaimportowanej implementacji. W pełni kwalifikowana składnia nie jest tu potrzebna.
"""

[[questions]]
id = "cb7e4d54-e95b-4153-99d6-e8f380e4f8b4"
type = "MultipleChoice"
prompt.prompt = """
Rozważ implementację traitu `Trait` dla typu `T`. W których z poniższych sytuacji
musisz opakować `T` w typ newtype?
"""
answer.answer = [
    "`Trait` jest zdefiniowany w zewnętrznym crate’cie i `T` jest zdefiniowany w zewnętrznym crate’cie",
]
prompt.distractors = [
    "`Trait` jest zdefiniowany w lokalnym crate’cie, a `T` w zewnętrznym crate’cie",
    "`Trait` jest zdefiniowany w zewnętrznym crate’cie, a `T` w lokalnym crate’cie",
    "`Trait` jest zdefiniowany w lokalnym crate’cie i `T` jest zdefiniowany w lokalnym crate’cie",
]
context = """
Reguła sieroty mówi, że traitu nie można zaimplementować dla typu, jeśli oba są
zdefiniowane w zewnętrznym crate’cie, co wymusza użycie wzorca newtype. Jeśli trait lub typ
jest zdefiniowany lokalnie, wzorzec newtype nie jest potrzebny.
"""
