[[questions]]
id = "d172fc53-0220-4ff4-83c9-9c0a6834dd8e"
type = "MultipleChoice"
prompt.prompt = "Ile to jest 1 + 1? (Spróbuj kliknąć błędną odpowiedź.)"
answer.answer = "2"
prompt.distractors = [ "0", "-999", "11" ]
context = """
Wyjaśnienie tego faktu znajdziesz w *Principia Mathematica*.
"""